"""Build the MO2 profile (mod order, plugin order, ini files) from install.json.

Consumes the `install.json` written by the installer step (see the module docstring
in `installer.py`) plus the original `collection.json` manifest, and writes a
portable MO2 instance under `--mo2-dir`: `ModOrganizer.ini`, `downloads/`,
`overwrite/`, and `profiles/<profile>/{modlist,plugins,loadorder}.txt` +
`settings.ini`. Mod order is derived from the manifest's install `phase` plus any
`modRules` that resolve to two mods actually present in the collection; plugin
order is derived from mod order plus the manifest's own `plugins[]` load order.
"""

from __future__ import annotations

import argparse
import configparser
import heapq
import json
import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from . import ledger as ledger_mod
from .manifest import load_manifest
from .naming import layer_separator_name, sanitize_folder_name, separator_name
from .reporter import Reporter, get_reporter

# MO2 short game name -> the game plugin's display name (ModOrganizer.ini gameName=).
MO2_GAME_DISPLAY_NAMES: dict[str, str] = {
    "SkyrimSE": "Skyrim Special Edition",
    "Skyrim": "Skyrim",
    "SkyrimVR": "Skyrim VR",
    "Fallout4": "Fallout 4",
    "FalloutNV": "New Vegas",
    "Fallout3": "Fallout 3",
    "Oblivion": "Oblivion",
    "Starfield": "Starfield",
    "Enderal": "Enderal",
    "EnderalSE": "Enderal Special Edition",
}

# Base-game master files that MO2 adds itself and that should never be written to
# plugins.txt / loadorder.txt even if a mod entry happens to list one.
BASE_GAME_MASTERS: dict[str, set[str]] = {
    "SkyrimSE": {"skyrim.esm", "update.esm", "dawnguard.esm", "hearthfires.esm", "dragonborn.esm"},
    "Skyrim": {"skyrim.esm", "update.esm", "dawnguard.esm", "hearthfires.esm", "dragonborn.esm"},
    "SkyrimVR": {
        "skyrim.esm",
        "skyrimvr.esm",
        "update.esm",
        "dawnguard.esm",
        "hearthfires.esm",
        "dragonborn.esm",
    },
    "Fallout4": {
        "fallout4.esm",
        "dlcrobot.esm",
        "dlcworkshop01.esm",
        "dlccoast.esm",
        "dlcworkshop02.esm",
        "dlcworkshop03.esm",
        "dlcnukaworld.esm",
    },
    "FalloutNV": {"falloutnv.esm"},
    "Fallout3": {"fallout3.esm"},
    "Oblivion": {"oblivion.esm"},
}

SEP_SUFFIX = "_separator"
SEPARATOR_META = "[General]\nmodid=0\nversion=\nnewestVersion=\ncategory=0\ninstallationFile=\n"
SETTINGS_INI = "[General]\nLocalSaves=false\nLocalSettings=true\nAutomaticArchiveInvalidation=true\n"
HEADER = "# This file was automatically generated by Mod Organizer."
DLC_LINES = ["*DLC: Dragonborn", "*DLC: HearthFires", "*DLC: Dawnguard"]
PLUGIN_EXTS = {".esp", ".esm", ".esl"}

# modlist.txt rows MO2 writes for itself: the DLCs and every Creation Club plugin it
# finds in the game folder. They are not mod folders, they belong to no layer, and
# re-rendering the profile has to leave them exactly where MO2 put them.
MO2_PSEUDO_PREFIXES = ("DLC: ", "Creation Club: ")


# -- Ordering -------------------------------------------------------------------


@dataclass
class OrderReport:
    order_idx: list[int]
    folders: list[str]
    rules_total: int
    rules_applied: int
    rules_ignored: int
    rules_conflicts: int
    rules_unsupported: int
    cycle_breaks: int
    phase_crossings: int
    warnings: list[str] = field(default_factory=list)


def _phase_base_key(phase: Any) -> tuple[int, Any]:
    """Sort key placing optional-phase (666) mods after every numbered phase."""
    if phase == 666:
        return (1, 0)
    return (0, phase)


def _index_manifest_mods(mods: list[dict[str, Any]]) -> tuple[dict[str, dict], dict[str, dict]]:
    by_md5: dict[str, dict] = {}
    by_logical: dict[str, dict] = {}
    for mod in mods:
        src = mod.get("source") or {}
        md5 = src.get("md5")
        logical = src.get("logicalFilename")
        if md5:
            by_md5.setdefault(md5, mod)
        if logical:
            by_logical.setdefault(logical, mod)
    return by_md5, by_logical


def _resolve_endpoint(
    endpoint: dict[str, Any], by_md5: dict[str, dict], by_logical: dict[str, dict]
) -> dict | None:
    md5 = endpoint.get("fileMD5")
    if md5 and md5 in by_md5:
        return by_md5[md5]
    logical = endpoint.get("logicalFileName")
    if logical and logical in by_logical:
        return by_logical[logical]
    return None


def _entry_lookup(entries: list[dict[str, Any]]) -> tuple[dict[str, int], dict[tuple, int]]:
    by_md5: dict[str, int] = {}
    by_modfile: dict[tuple, int] = {}
    for i, e in enumerate(entries):
        md5 = e.get("md5")
        if md5:
            by_md5.setdefault(md5, i)
        mod_id, file_id = e.get("mod_id"), e.get("file_id")
        if mod_id is not None and file_id is not None:
            by_modfile.setdefault((mod_id, file_id), i)
    return by_md5, by_modfile


def _entry_index_for_mod(
    mod: dict[str, Any], by_md5: dict[str, int], by_modfile: dict[tuple, int]
) -> int | None:
    src = mod.get("source") or {}
    md5 = src.get("md5")
    if md5 and md5 in by_md5:
        return by_md5[md5]
    key = (src.get("modId"), src.get("fileId"))
    if key in by_modfile:
        return by_modfile[key]
    return None


@dataclass
class RuleStats:
    """How a set of `modRules` fared against a set of install entries."""

    total: int = 0
    applied: int = 0
    ignored: int = 0
    conflicts: int = 0
    unsupported: int = 0


def _collect_edges(
    rules: list[dict[str, Any]],
    entries: list[dict[str, Any]],
    mod_by_md5: dict[str, dict],
    mod_by_logical: dict[str, dict],
    entries_by_md5: dict[str, int],
    entries_by_modfile: dict[tuple, int],
    warnings: list[str],
    stats: RuleStats,
) -> list[tuple[int, int]]:
    """Turn `before`/`after` rules into `(earlier, later)` edges over `entries`.

    Endpoints are resolved through the *given* manifest indexes, which is what makes
    cross-layer rules work: pass the union of every layer's mods and an add-on's rule
    can name a base-collection mod by md5 and still order against it.
    """
    edges: list[tuple[int, int]] = []
    for rule in rules:
        stats.total += 1
        rtype = rule.get("type")
        src_mod = _resolve_endpoint(rule.get("source") or {}, mod_by_md5, mod_by_logical)
        ref_mod = _resolve_endpoint(rule.get("reference") or {}, mod_by_md5, mod_by_logical)
        if src_mod is None or ref_mod is None:
            stats.ignored += 1
            continue

        src_idx = _entry_index_for_mod(src_mod, entries_by_md5, entries_by_modfile)
        ref_idx = _entry_index_for_mod(ref_mod, entries_by_md5, entries_by_modfile)
        if src_idx is None or ref_idx is None:
            stats.ignored += 1
            warnings.append(
                f"modRule ({rtype}) resolved to manifest mods with no matching install "
                f"entry: {src_mod.get('name')!r} / {ref_mod.get('name')!r}"
            )
            continue
        if src_idx == ref_idx:
            stats.ignored += 1
            continue

        if rtype == "before":
            edges.append((src_idx, ref_idx))
            stats.applied += 1
        elif rtype == "after":
            edges.append((ref_idx, src_idx))
            stats.applied += 1
        elif rtype == "conflicts":
            stats.conflicts += 1
            warnings.append(
                f"modRule conflicts: {entries[src_idx]['folder']!r} <-> "
                f"{entries[ref_idx]['folder']!r} (not reordered)"
            )
        else:
            stats.unsupported += 1
            warnings.append(f"modRule type {rtype!r} between collection mods ignored (unsupported)")
    return edges


def _toposort(
    n: int, edges: list[tuple[int, int]], base_rank: dict[int, int]
) -> tuple[list[int], int, set[int]]:
    """Stable topological sort: obey the edges, otherwise keep `base_rank` order.

    Returns `(order, cycle_breaks, cycle_members)`. A cycle is broken by emitting its
    lowest-ranked member, which degrades to base order rather than failing.
    """
    adjacency: dict[int, list[int]] = {i: [] for i in range(n)}
    indegree: dict[int, int] = {i: 0 for i in range(n)}
    seen_edges: set[tuple[int, int]] = set()
    for a, b in edges:
        if (a, b) in seen_edges:
            continue
        seen_edges.add((a, b))
        adjacency[a].append(b)
        indegree[b] += 1

    remaining = set(range(n))
    heap = [(base_rank[i], i) for i in remaining if indegree[i] == 0]
    heapq.heapify(heap)
    result_idx: list[int] = []
    cycle_breaks = 0
    cycle_members: set[int] = set()

    while remaining:
        if heap:
            _, node = heapq.heappop(heap)
            if node not in remaining:
                continue
        else:
            node = min(remaining, key=lambda i: base_rank[i])
            cycle_breaks += 1
            cycle_members.add(node)
        remaining.discard(node)
        result_idx.append(node)
        for succ in adjacency[node]:
            if succ in remaining:
                indegree[succ] -= 1
                if indegree[succ] == 0:
                    heapq.heappush(heap, (base_rank[succ], succ))
    return result_idx, cycle_breaks, cycle_members


def _compute_order(manifest: dict[str, Any], entries: list[dict[str, Any]]) -> OrderReport:
    n = len(entries)
    warnings: list[str] = []

    def base_key(i: int) -> tuple:
        return (*_phase_base_key(entries[i].get("phase", 0)), i)

    base_order = sorted(range(n), key=base_key)
    base_rank = {idx: rank for rank, idx in enumerate(base_order)}

    mods = manifest.get("mods") or []
    mod_by_md5, mod_by_logical = _index_manifest_mods(mods)
    entries_by_md5, entries_by_modfile = _entry_lookup(entries)

    rules = manifest.get("modRules") or []
    stats = RuleStats()
    edges = _collect_edges(
        rules,
        entries,
        mod_by_md5,
        mod_by_logical,
        entries_by_md5,
        entries_by_modfile,
        warnings,
        stats,
    )
    result_idx, cycle_breaks, cycle_members = _toposort(n, edges, base_rank)

    if cycle_breaks:
        warnings.append(
            f"modRules formed {cycle_breaks} cycle-break(s) among {len(cycle_members)} mod(s); "
            "kept base (phase/manifest) order for the affected mods"
        )

    rules_applied = stats.applied
    rules_ignored = stats.ignored
    rules_conflicts = stats.conflicts
    rules_unsupported = stats.unsupported

    phase_crossings = 0
    max_seen: tuple | None = None
    for idx in result_idx:
        pr = _phase_base_key(entries[idx].get("phase", 0))
        if max_seen is not None and pr < max_seen:
            phase_crossings += 1
        if max_seen is None or pr > max_seen:
            max_seen = pr

    folders = [entries[i]["folder"] for i in result_idx]

    return OrderReport(
        order_idx=result_idx,
        folders=folders,
        rules_total=len(rules),
        rules_applied=rules_applied,
        rules_ignored=rules_ignored,
        rules_conflicts=rules_conflicts,
        rules_unsupported=rules_unsupported,
        cycle_breaks=cycle_breaks,
        phase_crossings=phase_crossings,
        warnings=warnings,
    )


def order_mods(manifest: dict[str, Any], entries: list[dict[str, Any]]) -> list[str]:
    """Return mod folder names in MO2 priority order, lowest priority first."""
    return _compute_order(manifest, entries).folders


# -- Separators -------------------------------------------------------------------


@dataclass
class ProfileItem:
    kind: str  # "mod" | "separator"
    name: str
    entry_idx: int | None = None
    phase: Any = None


def build_items_with_separators(
    entries: list[dict[str, Any]],
    order_idx: list[int],
    sep_names: list[str | None],
    add_separators: bool,
) -> list[ProfileItem]:
    """Ascending-priority mod list with a separator inserted after each run of mods.

    `sep_names[i]` is the separator the entry at index `i` belongs under: the phase
    separator for a base-collection mod, the layer separator for an add-on's. A
    separator appears right after its run in this ascending (lowest-priority-first)
    list, which puts it directly above that group once the list is reversed for
    modlist.txt (MO2's descending-priority, top-to-bottom view).
    """
    items: list[ProfileItem] = []
    sep_name_counts: dict[str, int] = {}
    run_sep: str | None = None
    run_phase: Any = None
    run_started = False

    def close_run(name: str | None, phase: Any) -> None:
        if not add_separators or not name:
            return
        count = sep_name_counts.get(name, 0)
        sep_name_counts[name] = count + 1
        if count:
            # A rule pulled some mods across a phase (or layer) boundary, splitting the
            # group into several runs. One separator per group is enough; the stragglers
            # simply sit inside the neighbouring section.
            return
        items.append(ProfileItem(kind="separator", name=name, phase=phase))

    for idx in order_idx:
        sep = sep_names[idx]
        phase = entries[idx].get("phase", 0)
        if run_started and sep != run_sep:
            close_run(run_sep, run_phase)
        items.append(ProfileItem(kind="mod", name=entries[idx]["folder"], entry_idx=idx, phase=phase))
        run_sep = sep
        run_phase = phase
        run_started = True
    if run_started:
        close_run(run_sep, run_phase)
    return items


def build_profile_order(
    entries: list[dict[str, Any]], order_idx: list[int], add_separators: bool
) -> list[ProfileItem]:
    """Single-collection profile order: one separator per install phase."""
    sep_names = [separator_name(e.get("phase", 0)) for e in entries]
    return build_items_with_separators(entries, order_idx, sep_names, add_separators)


# -- Plugins ----------------------------------------------------------------------


def build_plugin_order(
    manifest: dict[str, Any], entries: list[dict[str, Any]], order_idx: list[int], game_name: str
) -> tuple[list[tuple[str, bool]], list[str], dict[str, int]]:
    """Plugin load order: manifest plugins[] order first, then extras in mod order."""
    manifest_plugins = manifest.get("plugins") or []
    base_masters = BASE_GAME_MASTERS.get(game_name, set())

    seen: set[str] = set()
    collected: list[tuple[str, int]] = []
    for idx in order_idx:
        for name in entries[idx].get("plugins") or []:
            low = name.lower()
            if low in base_masters or low in seen:
                continue
            seen.add(low)
            collected.append((name, idx))
    collected_by_lower = {name.lower(): (name, idx) for name, idx in collected}

    ordered: list[tuple[str, bool]] = []
    used_lower: set[str] = set()
    for p in manifest_plugins:
        name = p.get("name")
        if not name:
            continue
        low = name.lower()
        if low in base_masters or low in used_lower:
            continue
        if low in collected_by_lower:
            used_lower.add(low)
            ordered.append((name, bool(p.get("enabled", True))))

    warnings: list[str] = []
    extra_count = 0
    for name, idx in collected:
        low = name.lower()
        if low in used_lower:
            continue
        used_lower.add(low)
        ordered.append((name, True))
        extra_count += 1
        warnings.append(
            f"plugin {name!r} (from mod {entries[idx]['folder']!r}) is not in the manifest's "
            "plugins list; enabling by default (likely an unselected FOMOD alternative or an "
            "optional-mod plugin)"
        )

    stats = {"in_manifest": len(ordered) - extra_count, "extra": extra_count}
    return ordered, warnings, stats


# -- Rendering ----------------------------------------------------------------------


def _fwd(path: str | None) -> str:
    return (path or "").replace("\\", "/")


def render_modlist(
    items: list[ProfileItem],
    entries: list[dict[str, Any]],
    disable_optional: bool,
    game_name: str,
) -> str:
    lines = [HEADER]
    for item in reversed(items):
        if item.kind == "separator":
            lines.append(f"-{item.name}")
            continue
        e = entries[item.entry_idx]
        is_optional = bool(e.get("optional")) or e.get("phase") == 666
        enabled = not (is_optional and disable_optional)
        lines.append(f"{'+' if enabled else '-'}{e['folder']}")
    if game_name == "SkyrimSE":
        lines.extend(DLC_LINES)
    return "\n".join(lines) + "\n"


def render_plugins_txt(plugin_order: list[tuple[str, bool]]) -> str:
    lines = [HEADER]
    lines.extend(f"*{name}" if enabled else name for name, enabled in plugin_order)
    return "\n".join(lines) + "\n"


def render_loadorder_txt(plugin_order: list[tuple[str, bool]]) -> str:
    lines = [HEADER]
    lines.extend(name for name, _ in plugin_order)
    return "\n".join(lines) + "\n"


def build_custom_executables(
    entries: list[dict[str, Any]], tools: list[dict[str, Any]], game_path: str
) -> list[dict[str, str]]:
    gp = _fwd(game_path)
    blocks: list[dict[str, str]] = []

    has_script_extender_mod = any("Script Extender" in (e.get("folder") or "") for e in entries)
    has_dinput_skse = any(
        e.get("mod_type") == "dinput" and "SKSE" in (e.get("name") or e.get("folder") or "")
        for e in entries
    )
    if has_script_extender_mod or has_dinput_skse:
        binary = f"{gp}/skse64_loader.exe" if gp else "skse64_loader.exe"
        blocks.append(
            {
                "title": "SKSE",
                "binary": binary,
                "arguments": "",
                "workingDirectory": gp,
                "hide": "false",
                "ownicon": "true",
                "steamAppID": "",
                "toolbar": "true",
            }
        )

    seen_binaries = {b["binary"].lower() for b in blocks}
    for tool in tools:
        exe = _fwd(tool.get("exe") or "")
        binary = f"{gp}/{exe}" if gp else exe
        if binary.lower() in seen_binaries:
            continue  # the manifest lists SKSE too; keep our single entry
        seen_binaries.add(binary.lower())
        # A curator's cwd is their own machine's path; only keep it if it exists here.
        raw_cwd = tool.get("cwd") or ""
        cwd = _fwd(raw_cwd) if raw_cwd and Path(raw_cwd).exists() else gp
        args = tool.get("args") or []
        blocks.append(
            {
                "title": tool.get("name") or "",
                "binary": binary,
                "arguments": " ".join(str(a) for a in args),
                "workingDirectory": cwd,
                "hide": "false",
                "ownicon": "true",
                "steamAppID": "",
                "toolbar": "true",
            }
        )
    return blocks


def render_mo2_ini(
    game_name: str,
    game_path: str,
    profile_name: str,
    mo2_version: str,
    exe_blocks: list[dict[str, str]],
) -> str:
    display_name = MO2_GAME_DISPLAY_NAMES.get(game_name, game_name)
    # MO2 stores gamePath as a QByteArray with native separators, backslashes doubled.
    # Writing it in that form (plus game_edition) makes the instance recognisable as a
    # portable one without needing `build` to rewrite it afterwards.
    native = game_path.replace("/", "\\").replace("\\", "\\\\") if game_path else ""
    game_path_line = f"gamePath=@ByteArray({native})" if game_path else "gamePath="
    lines = [
        "[General]",
        f"gameName={display_name}",
        game_path_line,
        f"selected_profile=@ByteArray({profile_name})",
        f"version={mo2_version}",
        "first_start=false",
        "game_edition=Steam",
        "",
        "[Settings]",
        "style=",
        "",
        "[customExecutables]",
        f"size={len(exe_blocks)}",
    ]
    for i, b in enumerate(exe_blocks, start=1):
        lines.append(f"{i}\\title={b['title']}")
        lines.append(f"{i}\\binary={b['binary']}")
        lines.append(f"{i}\\arguments={b['arguments']}")
        lines.append(f"{i}\\workingDirectory={b['workingDirectory']}")
        lines.append(f"{i}\\hide={b['hide']}")
        lines.append(f"{i}\\ownicon={b['ownicon']}")
        lines.append(f"{i}\\steamAppID={b['steamAppID']}")
        lines.append(f"{i}\\toolbar={b['toolbar']}")
    return "\n".join(lines) + "\n"


def _write(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8", newline="\n")


def _write_keeping_newlines(path: Path, text: str) -> None:
    """Write a profile file, keeping the line ending the existing file already uses.

    MO2 rewrites `plugins.txt` / `loadorder.txt` with CRLF the first time the instance
    is opened. Re-rendering the profile with LF would then show every line as changed
    to anything diffing the instance, for no reason at all, so match what is there.
    """
    newline = "\n"
    if path.exists():
        try:
            with open(path, "rb") as fh:
                if b"\r\n" in fh.read(65536):
                    newline = "\r\n"
        except OSError:
            pass
    path.write_text(text, encoding="utf-8", newline=newline)


# -- Command ----------------------------------------------------------------------


# -- Profile-local game INIs -------------------------------------------------------

# MO2 short game name -> (My Games folder, [INI basenames], vanilla default INI in the game dir)
GAME_INIS: dict[str, tuple[str, list[str], str]] = {
    "SkyrimSE": ("Skyrim Special Edition", ["Skyrim.ini", "SkyrimPrefs.ini", "SkyrimCustom.ini"], "Skyrim_Default.ini"),
    "SkyrimVR": ("Skyrim VR", ["Skyrim.ini", "SkyrimPrefs.ini", "SkyrimCustom.ini"], "Skyrim_Default.ini"),
    "Skyrim": ("Skyrim", ["Skyrim.ini", "SkyrimPrefs.ini"], "Skyrim_default.ini"),
    "Fallout4": ("Fallout4", ["Fallout4.ini", "Fallout4Prefs.ini", "Fallout4Custom.ini"], "Fallout4_Default.ini"),
    "FalloutNV": ("FalloutNV", ["Fallout.ini", "FalloutPrefs.ini"], "Fallout_default.ini"),
    "Fallout3": ("Fallout3", ["Fallout.ini", "FalloutPrefs.ini"], "Fallout_default.ini"),
    "Oblivion": ("Oblivion", ["Oblivion.ini"], "Oblivion_default.ini"),
    "Starfield": ("Starfield", ["Starfield.ini", "StarfieldPrefs.ini", "StarfieldCustom.ini"], "Starfield_Default.ini"),
}


def seed_profile_inis(profile_dir: Path, game_name: str, game_path: str) -> tuple[list[str], list[str]]:
    """Create the profile-local game INIs MO2 expects when LocalSettings=true.

    Prefers the user's current INIs from Documents/My Games (they already match the
    installed game version), falls back to the game's shipped *_Default.ini for the
    main INI and empty files for the rest. Existing profile INIs are left alone.

    Returns `(files_written, notes)`; `notes` is a single-element list summarising where the
    written INIs came from (My Games path / *_Default.ini / empty), so users can tell why a
    profile INI has (or lacks) particular values.
    """
    spec = GAME_INIS.get(game_name)
    if not spec:
        return [], []
    my_games_dir, names, default_ini = spec
    my_games = Path.home() / "Documents" / "My Games" / my_games_dir
    written: list[str] = []
    sources: list[str] = []
    for i, name in enumerate(names):
        dest = profile_dir / name
        if dest.exists():
            continue
        src = my_games / name
        if src.exists():
            shutil.copy2(src, dest)
            source = f"My Games ({my_games})"
        elif i == 0 and game_path and (Path(game_path) / default_ini).exists():
            shutil.copy2(Path(game_path) / default_ini, dest)
            source = f"game default ({Path(game_path) / default_ini})"
        else:
            dest.write_text("", encoding="utf-8")
            source = "empty (no source found)"
        written.append(str(dest))
        if source not in sources:
            sources.append(source)

    if not written:
        notes = ["seed INIs: none written (profile INIs already existed)"]
    else:
        notes = [f"seed INIs from: {'; '.join(sources)}"]
    return written, notes


_INI_TWEAK_TARGET = re.compile(r"\[([^\[\]]+)\]\.ini$", re.IGNORECASE)


def _section_ranges(lines: list[str], section: str) -> list[tuple[int, int]]:
    """`(header index, first line after the section)` for every `[section]` block.

    Bethesda game INIs occasionally end up with a section duplicated -- BethINI, the
    vanilla launcher, and hand edits over a long modding history all just append rather
    than merge, and a Vortex/My Games INI we seed a profile from can already carry one.
    Their own INI reader (and Windows' GetPrivateProfileString-style parsing) resolves a
    duplicate key by taking the *last* occurrence, so a writer that only ever touches the
    first `[section]` it finds can leave a stale duplicate elsewhere in the file silently
    winning at runtime -- see `merge_ini_values`.
    """
    starts = [i for i, ln in enumerate(lines) if ln.strip().lower() == f"[{section.lower()}]"]
    ranges = []
    for start in starts:
        end = next(
            (i for i in range(start + 1, len(lines)) if lines[i].strip().startswith("[")),
            len(lines),
        )
        ranges.append((start, end))
    return ranges


def _section_bounds(lines: list[str], section: str) -> tuple[int, int] | None:
    """`(header index, first line after the section)` for the first `[section]`, or None."""
    ranges = _section_ranges(lines, section)
    return ranges[0] if ranges else None


def _find_key(lines: list[str], start: int, end: int, key: str) -> int | None:
    return next(
        (
            i
            for i in range(start + 1, end)
            if lines[i].split("=", 1)[0].strip().lower() == key.lower()
        ),
        None,
    )


def merge_ini_values(
    target: Path,
    section: str,
    values: dict[str, str],
    record: dict[str, dict[str, Any]] | None = None,
) -> int:
    """Set/override `values` (key -> value) within `section` of a game INI, line-based.

    Comments, ordering and odd lines elsewhere in the file survive; the section is created
    at the end of the file if missing, and unknown keys are appended within it. Returns the
    number of keys applied.

    If `[section]` is duplicated in the file, every existing occurrence of a key is set to
    the same value (not just the first one found), and a key with no existing occurrence at
    all is inserted into the *last* `[section]` block. Bethesda's INI reader resolves a
    duplicate key by taking the last occurrence, so this is what makes the applied value the
    one that actually wins at runtime instead of a stale earlier duplicate silently
    overriding it (see `_section_ranges`).

    When `record` is given it collects `{key: {"value", "previous"}}`: the value written and
    the one that was there before it (`None` when the key did not exist). That pair is what
    lets a collection layer be removed later without disturbing keys the user -- or an
    earlier layer -- set.
    """
    lines = target.read_text(encoding="utf-8-sig").splitlines() if target.exists() else []
    if not _section_ranges(lines, section):
        if lines and lines[-1].strip():
            lines.append("")
        lines.append(f"[{section}]")

    applied = 0
    for key, value in values.items():
        new_line = f"{key}={value}"
        # Re-resolved every iteration: an earlier key in this same call may have inserted
        # a line and shifted every range after it.
        ranges = _section_ranges(lines, section)
        hits = [h for start, end in ranges for h in (_find_key(lines, start, end, key),) if h is not None]
        if hits:
            previous = lines[hits[0]].split("=", 1)[1] if "=" in lines[hits[0]] else None
            for hit in hits:
                lines[hit] = new_line
        else:
            previous = None
            _, last_end = ranges[-1]
            lines.insert(last_end, new_line)
        if record is not None:
            record[key] = {"value": str(value), "previous": previous}
        applied += 1
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return applied


def restore_ini_values(target: Path, section: str, values: dict[str, Any]) -> tuple[int, int]:
    """Undo `merge_ini_values`: put back each key's `previous`, or delete it if there was none.

    `values` is `{key: {"value", "previous"}}` as recorded in the ledger. A key whose current
    value no longer matches what the layer wrote has been changed by hand since, so it is
    left alone. Mirrors `merge_ini_values`: every occurrence of the key across a duplicated
    `[section]` is put back (or removed), not just the first one. Returns `(restored, deleted)`.
    """
    if not target.exists():
        return 0, 0
    lines = target.read_text(encoding="utf-8-sig").splitlines()
    if not _section_ranges(lines, section):
        return 0, 0
    restored = deleted = 0
    for key, info in values.items():
        ranges = _section_ranges(lines, section)
        hits = [h for start, end in ranges for h in (_find_key(lines, start, end, key),) if h is not None]
        if not hits:
            continue
        current = lines[hits[0]].split("=", 1)[1] if "=" in lines[hits[0]] else None
        wrote = info.get("value")
        if wrote is not None and current is not None and current.strip() != str(wrote).strip():
            continue  # edited since we wrote it; not ours to undo
        previous = info.get("previous")
        if previous is None:
            for hit in sorted(hits, reverse=True):
                del lines[hit]
            deleted += 1
        else:
            for hit in hits:
                lines[hit] = f"{key}={previous}"
            restored += 1
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return restored, deleted


def revert_ini_keys(profile_dir: Path, ini_keys: dict[str, dict[str, Any]]) -> list[str]:
    """Revert every INI key a layer recorded in the ledger; one note per INI file touched."""
    notes: list[str] = []
    for ini_name, sections in (ini_keys or {}).items():
        target = profile_dir / ini_name
        restored = deleted = 0
        for section, values in sections.items():
            name = section.strip()[1:-1] if section.strip().startswith("[") else section
            r, d = restore_ini_values(target, name, values)
            restored += r
            deleted += d
        if restored or deleted:
            notes.append(f"INI reverted: {ini_name} ({restored} restored, {deleted} removed)")
    return notes


def merge_ini_tweak(
    target: Path, tweak: Path, record: dict[str, dict[str, dict[str, Any]]] | None = None
) -> int:
    """Apply a Vortex INI tweak file onto a game INI: set/override each key in its section.

    Line-based (via `merge_ini_values`) so comments, ordering and odd lines in the game INI
    survive. Returns the number of keys applied. When `record` is given it collects
    `{"[Section]": {key: {"value", "previous"}}}` for the instance ledger, so a later
    `c2wj remove` knows exactly which INI keys this layer is responsible for and what value
    to put back in their place.
    """
    tweak_cp = configparser.RawConfigParser(strict=False, delimiters=("=",), interpolation=None)
    tweak_cp.optionxform = str  # type: ignore[assignment]
    tweak_cp.read(tweak, encoding="utf-8-sig")

    applied = 0
    for section in tweak_cp.sections():
        values = dict(tweak_cp.items(section))
        bucket = record.setdefault(f"[{section}]", {}) if record is not None and values else None
        applied += merge_ini_values(target, section, values, bucket)
    return applied


def apply_collection_ini_tweaks(
    profile_dir: Path,
    archive_dir: Path,
    game_name: str,
    record: dict[str, dict[str, dict[str, Any]]] | None = None,
) -> list[str]:
    """Apply the collection archive's `INI Tweaks/<name> [Skyrim].ini` files to the profile INIs.

    `record`, when given, collects `{"<ini file>": {"[Section]": [key, ...]}}`.
    """
    tweaks_dir = archive_dir / "INI Tweaks"
    if not tweaks_dir.is_dir():
        return []
    spec = GAME_INIS.get(game_name)
    known = {n.lower()[:-4]: n for n in (spec[1] if spec else [])}  # "skyrimprefs" -> "SkyrimPrefs.ini"
    notes: list[str] = []
    for tweak in sorted(tweaks_dir.glob("*.ini")):
        m = _INI_TWEAK_TARGET.search(tweak.name)
        target_name = known.get(m.group(1).lower()) if m else None
        if not target_name:
            notes.append(f"INI tweak skipped (cannot tell which INI it targets): {tweak.name}")
            continue
        into = record.setdefault(target_name, {}) if record is not None else None
        n = merge_ini_tweak(profile_dir / target_name, tweak, into)
        notes.append(f"INI tweak applied: {tweak.name} -> {target_name} ({n} keys)")
    return notes


def _prefs_ini_name(game_name: str) -> str | None:
    """The `*Prefs.ini` (display settings) file for a game, per `GAME_INIS`."""
    spec = GAME_INIS.get(game_name)
    if not spec:
        return None
    names = spec[1]
    if not names:
        return None
    return next((n for n in names if "prefs" in n.lower()), names[0])


def _detect_resolution() -> tuple[int, int] | None:
    """Detect the primary monitor's current resolution on Windows via ctypes.

    Returns `None` (caller falls back to `keep`) on non-Windows platforms or if the Win32
    calls fail for any reason.
    """
    import sys

    if sys.platform != "win32":
        return None
    try:
        import ctypes

        user32 = ctypes.windll.user32  # type: ignore[attr-defined]
        user32.SetProcessDPIAware()
        width = user32.GetSystemMetrics(0)
        height = user32.GetSystemMetrics(1)
    except Exception:  # noqa: BLE001 - detection is best-effort, fall back to keep
        return None
    if width <= 0 or height <= 0:
        return None
    return width, height


_RESOLUTION_RE = re.compile(r"^(\d+)x(\d+)$", re.IGNORECASE)


def _parse_resolution_arg(value: str) -> str:
    """argparse `type=` for --resolution: 'auto', 'keep', or WxH, validated at parse time."""
    if value in ("auto", "keep") or _RESOLUTION_RE.match(value):
        return value
    raise argparse.ArgumentTypeError(f"must be 'auto', 'keep', or WxH e.g. 3440x1440 (got {value!r})")


@dataclass
class DisplayChoice:
    """The user's --resolution/--vsync/--window request, resolved to concrete values.

    `None` on any field means "keep" (or, for resolution, that `auto`-detection failed).
    Shared between `apply_display_settings` (writes `*Prefs.ini` `[Display]`) and
    `apply_sse_display_tweaks_override` (writes the SSE Display Tweaks override mod) so
    'auto' detection and the fullscreen/borderless/windowed mapping are computed exactly
    once and applied identically to both files.
    """

    resolution_wh: tuple[int, int] | None
    resolution_label: str
    vsync_on: bool | None
    vsync_label: str
    window_word: str | None  # "fullscreen" | "borderless" | "windowed" | None (keep)
    window_label: str

    @property
    def is_keep(self) -> bool:
        return self.resolution_wh is None and self.vsync_on is None and self.window_word is None


def _resolve_display_choice(resolution: str, vsync: str, window: str) -> DisplayChoice:
    """Turn the raw --resolution/--vsync/--window strings into a `DisplayChoice`.

    `resolution` is `auto` (detect the primary monitor via Windows APIs, falling back to
    `keep` if that's not possible), `keep`, or an explicit `WxH` string. `vsync` is
    `on`/`off`/`keep`; `window` is `fullscreen`/`borderless`/`windowed`/`keep`.
    """
    if resolution == "keep":
        res_wh, res_label = None, "kept"
    elif resolution == "auto":
        detected = _detect_resolution()
        if detected:
            res_wh, res_label = detected, f"{detected[0]}x{detected[1]}"
        else:
            res_wh, res_label = None, "kept (auto-detect unavailable)"
    else:
        m = _RESOLUTION_RE.match(resolution)
        if not m:
            raise ValueError(f"--resolution must be 'auto', 'keep', or WxH (got {resolution!r})")
        res_wh = (int(m.group(1)), int(m.group(2)))
        res_label = f"{res_wh[0]}x{res_wh[1]}"

    if vsync == "on":
        vsync_on, vsync_label = True, "on"
    elif vsync == "off":
        vsync_on, vsync_label = False, "off"
    else:
        vsync_on, vsync_label = None, "kept"

    if window in ("fullscreen", "borderless", "windowed"):
        window_word, window_label = window, window
    else:
        window_word, window_label = None, "kept"

    return DisplayChoice(res_wh, res_label, vsync_on, vsync_label, window_word, window_label)


def apply_display_settings(
    profile_dir: Path,
    game_name: str,
    resolution: str,
    vsync: str,
    window: str,
    record: dict[str, dict[str, dict[str, Any]]] | None = None,
) -> list[str]:
    """Apply --resolution/--vsync/--window overrides to the profile's `*Prefs.ini` [Display].

    Applied after the collection's own INI Tweaks, so these settings win over them --
    though not over a collection's SSE Display Tweaks file, which bypasses SkyrimPrefs.ini
    entirely when present; see `apply_sse_display_tweaks_override`. Returns a
    single-element list with a human-readable summary line of the values actually written
    (empty list if the game has no known Prefs INI).
    """
    target_name = _prefs_ini_name(game_name)
    if not target_name:
        return []
    target = profile_dir / target_name
    choice = _resolve_display_choice(resolution, vsync, window)

    values: dict[str, str] = {}
    if choice.resolution_wh is not None:
        values["iSize W"] = str(choice.resolution_wh[0])
        values["iSize H"] = str(choice.resolution_wh[1])
    if choice.vsync_on is not None:
        values["iVSyncPresentInterval"] = "1" if choice.vsync_on else "0"
    # Skyrim SE's launcher writes borderless as bFull Screen=1 + bBorderless=1.
    if choice.window_word == "fullscreen":
        values["bFull Screen"] = "1"
        values["bBorderless"] = "0"
    elif choice.window_word == "borderless":
        values["bFull Screen"] = "1"
        values["bBorderless"] = "1"
    elif choice.window_word == "windowed":
        values["bFull Screen"] = "0"
        values["bBorderless"] = "0"

    if values:
        bucket = record.setdefault(target_name, {}).setdefault("[Display]", {}) if record else None
        merge_ini_values(target, "Display", values, bucket)

    return [
        (
            f"display: {choice.resolution_label}, vsync {choice.vsync_label}, "
            f"window {choice.window_label} ({target_name})"
        )
    ]


# -- SSE Display Tweaks awareness -------------------------------------------------------
#
# SSE Display Tweaks (`SKSE/Plugins/SSEDisplayTweaks.ini`) replaces SkyrimPrefs.ini's
# `[Display]` section wholesale when the SKSE plugin is present -- the game never
# consults SkyrimPrefs.ini's resolution/fullscreen/vsync keys at all in that case, so
# `apply_display_settings` alone can be silently overridden by a collection that ships
# it. When that happens we instead layer a small, user-owned mod on top carrying our own
# copy of the *winning* collection file with just the requested keys rewritten --
# refreshed from that file on every render (so a collection update to its own Display
# Tweaks settings is still picked up) and pinned to the top of modlist.txt (so it always
# wins the MO2 virtual filesystem merge).

DISPLAY_TWEAKS_RELPATH = "SKSE/Plugins/SSEDisplayTweaks.ini"
DISPLAY_OVERRIDE_MOD_NAME = "c2wj Display Settings"
DISPLAY_OVERRIDE_MARKER = "c2wj-display"

def find_winning_file(
    modlist_path: Path, mods_dir: Path, relpath: str, *, skip: set[str] | None = None
) -> tuple[str, Path] | None:
    """The highest-priority *enabled* mod carrying `relpath`, per `modlist_path`.

    `modlist_path` is an already-rendered `modlist.txt`: top-to-bottom is MO2's own
    descending-priority view (the row nearest the top wins the virtual-filesystem merge),
    so this returns the first enabled row whose mod folder has the file. Disabled (`-`)
    rows and MO2's own DLC/Creation-Club pseudo-rows are skipped, as is anything named in
    `skip` (used to keep our own generated override mod from "winning" against itself on
    a later render). Returns `(mod_folder, path)`, or `None` if no enabled mod has it.
    """
    skip = skip or set()
    relpath = relpath.replace("\\", "/")
    for marker, name in read_marked_lines(modlist_path):
        if marker == "-" or name.startswith(MO2_PSEUDO_PREFIXES) or name in skip:
            continue
        candidate = mods_dir / name / Path(relpath)
        if candidate.is_file():
            return name, candidate
    return None


def _read_ini_key_anywhere(text: str, key: str) -> str | None:
    """First value for `key` anywhere in an INI's text, ignoring section boundaries."""
    low = key.lower()
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith((";", "#")) or "=" not in stripped:
            continue
        k, _, v = stripped.partition("=")
        if k.strip().lower() == low:
            return v.strip()
    return None


def _sse_display_tweaks_summary(mod_name: str, text: str) -> str:
    """The informative 'keep' line: what the winning SSE Display Tweaks file will do."""
    resolution = _read_ini_key_anywhere(text, "Resolution") or "?"
    fullscreen = (_read_ini_key_anywhere(text, "Fullscreen") or "").strip().lower()
    borderless = (_read_ini_key_anywhere(text, "Borderless") or "").strip().lower()
    vsync = (_read_ini_key_anywhere(text, "EnableVSync") or "").strip().lower()
    if borderless in ("true", "1"):
        window_word = "borderless"
    elif fullscreen in ("true", "1"):
        window_word = "fullscreen"
    else:
        window_word = "windowed"
    vsync_word = "on" if vsync in ("true", "1") else "off"
    return (
        f"SSE Display Tweaks (from mod {mod_name!r}) governs the display: "
        f"Resolution {resolution}, {window_word}, vsync {vsync_word} -- SkyrimPrefs "
        "values are ignored while it is enabled; set --resolution/--window/--vsync to override"
    )


def _display_tweaks_key(line: str) -> str | None:
    """The key a line sets, lower-cased -- whether the line is commented out or not.

    SSE Display Tweaks ships every key commented out with its default value as
    documentation (`#Fullscreen=false`); a plain key search that skips comments (as
    `_read_ini_key_anywhere` deliberately does, to know what is *actually* active) would
    never find where to put our own value. This is only for locating the right line to
    overwrite/uncomment.
    """
    body = line.strip().lstrip("#;").strip()
    if "=" not in body:
        return None
    return body.split("=", 1)[0].strip().lower()


def _rewrite_display_tweaks_ini(dest: Path, source_text: str, choice: DisplayChoice) -> None:
    """Write `dest` as a copy of `source_text` with `choice`'s keys rewritten in place.

    Every other line -- comments, ordering, unrelated keys -- survives untouched. A key
    already present (active or commented-out, wherever it lives -- this SKSE plugin's own
    schema is not assumed) is overwritten/uncommented in place; every duplicate occurrence
    is set the same way, since which one a parser honours is not something to gamble on.
    A key missing entirely is appended to its `[Render]` section (where every known
    version of this SKSE plugin keeps these four), or the end of the file if there is
    none.
    """
    dest.parent.mkdir(parents=True, exist_ok=True)

    wanted: dict[str, str] = {}
    if choice.resolution_wh is not None:
        wanted["Resolution"] = f"{choice.resolution_wh[0]}x{choice.resolution_wh[1]}"
    if choice.window_word == "fullscreen":
        wanted["Fullscreen"], wanted["Borderless"] = "true", "false"
    elif choice.window_word == "borderless":
        wanted["Fullscreen"], wanted["Borderless"] = "false", "true"
    elif choice.window_word == "windowed":
        wanted["Fullscreen"], wanted["Borderless"] = "false", "false"
    if choice.vsync_on is not None:
        wanted["EnableVSync"] = "true" if choice.vsync_on else "false"

    lines = source_text.splitlines()
    for key, value in wanted.items():
        hits = [i for i, ln in enumerate(lines) if _display_tweaks_key(ln) == key.lower()]
        if hits:
            for i in hits:
                lines[i] = f"{key}={value}"
            continue
        start = next(
            (i for i, ln in enumerate(lines) if ln.strip().lower() == "[render]"), None
        )
        if start is None:
            lines.append(f"{key}={value}")
        else:
            end = next(
                (i for i in range(start + 1, len(lines)) if lines[i].strip().startswith("[")),
                len(lines),
            )
            lines.insert(end, f"{key}={value}")

    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")


_DISPLAY_OVERRIDE_META_TEMPLATE = """[General]
modid=0
version=
newestVersion=
category=0
installationFile=
repository=
gameName={game_name}
comments=owner: user
notes=Generated by c2wj ({marker}) to keep your --resolution/--window/--vsync choice in \
effect over this collection's SSE Display Tweaks. Refreshed from the winning \
SSEDisplayTweaks.ini on every render; delete this mod to fall back to the collection's \
own settings.
nexusFileStatus=1
hasCustomURL=false
validated=true
converted=false
"""


def apply_sse_display_tweaks_override(
    profile_dir: Path,
    mods_dir: Path,
    game_name: str,
    resolution: str,
    vsync: str,
    window: str,
    led: ledger_mod.Ledger,
) -> list[str]:
    """Keep the user's display choice in effect over a collection's SSE Display Tweaks.

    Call after `apply_display_settings` and after `modlist.txt` has been written for this
    render. No-op (returns `[]`) if no enabled mod ships
    `SKSE/Plugins/SSEDisplayTweaks.ini`. Otherwise: if the user asked for anything other
    than 'keep', creates/refreshes the `DISPLAY_OVERRIDE_MOD_NAME` mod and pins it to the
    top of `modlist.txt`; if everything is 'keep', touches nothing and just reports what
    the winning file will do.
    """
    modlist_path = profile_dir / "modlist.txt"
    winning = find_winning_file(
        modlist_path, mods_dir, DISPLAY_TWEAKS_RELPATH, skip={DISPLAY_OVERRIDE_MOD_NAME}
    )
    if winning is None:
        return []
    mod_name, source_path = winning
    source_text = source_path.read_text(encoding="utf-8-sig")
    choice = _resolve_display_choice(resolution, vsync, window)

    if choice.is_keep:
        return [_sse_display_tweaks_summary(mod_name, source_text)]

    override_root = mods_dir / DISPLAY_OVERRIDE_MOD_NAME
    dest = override_root / Path(DISPLAY_TWEAKS_RELPATH)
    _rewrite_display_tweaks_ini(dest, source_text, choice)

    meta = override_root / "meta.ini"
    if not meta.exists():
        _write(
            meta,
            _DISPLAY_OVERRIDE_META_TEMPLATE.format(
                game_name=game_name, marker=f"generated_by: {DISPLAY_OVERRIDE_MARKER}"
            ),
        )

    record = led.set_mod_owner(DISPLAY_OVERRIDE_MOD_NAME, ledger_mod.USER_OWNER)
    record["generated_by"] = DISPLAY_OVERRIDE_MARKER

    # Pin to the very top of modlist.txt (highest priority) so it wins the merge.
    rows = [(m, n) for m, n in read_marked_lines(modlist_path) if n != DISPLAY_OVERRIDE_MOD_NAME]
    rows.insert(0, ("+", DISPLAY_OVERRIDE_MOD_NAME))
    _write_keeping_newlines(modlist_path, render_marked_lines(list(reversed(rows)), False))

    return [
        (
            f"SSE Display Tweaks override: {DISPLAY_OVERRIDE_MOD_NAME!r} generated from "
            f"{mod_name!r}, pinned to top priority (resolution {choice.resolution_label}, "
            f"vsync {choice.vsync_label}, window {choice.window_label})"
        )
    ]


# -- Layered instances --------------------------------------------------------------
#
# An instance is not one collection forever. `c2wj add` layers an add-on collection on
# top of the base one; the profile then has to be rendered from *all* the layers plus
# whatever the user installed by hand. The rules are:
#
#   mod order     base layer block (phase separators, as before), then each add-on's
#                 block in the order it was added, each behind its own separator.
#                 modRules are resolved across the union of every layer's mods, so an
#                 add-on's rule can order itself against a base mod; blocks stay
#                 contiguous unless such a rule forces otherwise (we warn when it does).
#   tool mods     folders `c2wj tools install` put in mods/ for a catalogue tool's
#                 companion mods (owner `tool:<id>`) go right after every layer's
#                 block, above the collection but below the user's own mods.
#   user mods     folders in mods/ the ledger does not own keep the position they have
#                 in the existing modlist.txt, relative to their surviving neighbours.
#   plugins       base manifest order, then each add-on's plugins that are not already
#                 listed; plugins belonging to user mods keep their existing state.
#   INI tweaks    applied layer by layer in order, each key recorded with the value it
#                 replaced so `c2wj remove` can put exactly that back.


@dataclass
class Layer:
    """One collection revision applied to an instance, as the profile writer sees it."""

    index: int
    slug: str
    revision: Any
    owner: str
    name: str
    manifest_path: Path
    manifest: dict[str, Any]
    entries: list[dict[str, Any]]

    @property
    def is_base(self) -> bool:
        return self.index == 0

    @property
    def archive_dir(self) -> Path:
        return self.manifest_path.parent

    @property
    def separator(self) -> str:
        return layer_separator_name(self.name, self.slug)


@dataclass
class LayeredOrder:
    """The union of every layer's install entries, ordered for one modlist.txt."""

    entries: list[dict[str, Any]]
    order_idx: list[int]
    sep_names: list[str]
    layer_of: list[int]
    sep_owner: dict[str, int]
    shared: dict[str, list[int]]
    rules: RuleStats
    cycle_breaks: int
    layer_crossings: int
    warnings: list[str] = field(default_factory=list)

    @property
    def folders(self) -> list[str]:
        return [self.entries[i]["folder"] for i in self.order_idx]


def instance_path(instance_dir: Path, value: str | None) -> Path | None:
    """Resolve a ledger path, which is relative to the instance so it stays movable."""
    if not value:
        return None
    path = Path(value)
    return path if path.is_absolute() else instance_dir / path


def load_layers(instance_dir: Path, led: ledger_mod.Ledger) -> tuple[list[Layer], list[str]]:
    """Read every ledger layer's manifest and install.json. Returns `(layers, warnings)`."""
    layers: list[Layer] = []
    warnings: list[str] = []
    for record in led.data.get("layers") or []:
        slug = record.get("slug") or ""
        revision = record.get("revision")
        manifest_path = instance_path(instance_dir, record.get("manifest"))
        install_path = instance_path(instance_dir, (record.get("files") or {}).get("install"))
        if manifest_path is None or not manifest_path.exists():
            warnings.append(f"layer {slug}@{revision}: manifest missing, skipped ({manifest_path})")
            continue
        if install_path is None or not install_path.exists():
            warnings.append(
                f"layer {slug}@{revision}: install.json missing, skipped ({install_path})"
            )
            continue
        try:
            install = json.loads(install_path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            warnings.append(f"layer {slug}@{revision}: install.json unreadable ({exc}), skipped")
            continue
        layers.append(
            Layer(
                index=len(layers),
                slug=slug,
                revision=revision,
                owner=ledger_mod.collection_owner(slug, revision),
                name=record.get("name") or slug,
                manifest_path=manifest_path,
                manifest=load_manifest(manifest_path),
                entries=install.get("entries") or [],
            )
        )
    return layers, warnings


def compute_layered_order(layers: list[Layer]) -> LayeredOrder:
    """Order the union of every layer's mods: layer blocks first, cross-layer rules on top."""
    entries: list[dict[str, Any]] = []
    layer_of: list[int] = []
    sep_names: list[str] = []
    sep_owner: dict[str, int] = {}
    index_of_folder: dict[str, int] = {}
    shared: dict[str, list[int]] = {}
    warnings: list[str] = []

    for layer in layers:
        local = _compute_order(layer.manifest, layer.entries)
        for idx in local.order_idx:
            source = layer.entries[idx]
            folder = source.get("folder") or ""
            if folder in index_of_folder:
                # The same archive under the same name: one folder, two layers.
                first = layer_of[index_of_folder[folder]]
                shared.setdefault(folder, [first]).append(layer.index)
                continue
            entry = dict(source)
            entry["layer"] = layer.index
            entry["layer_slug"] = layer.slug
            sep = separator_name(source.get("phase", 0)) if layer.is_base else layer.separator
            index_of_folder[folder] = len(entries)
            entries.append(entry)
            layer_of.append(layer.index)
            sep_names.append(sep)
            sep_owner.setdefault(sep, layer.index)

    # Rules from every layer, resolved against the union of every layer's mods.
    all_mods = [m for layer in layers for m in (layer.manifest.get("mods") or [])]
    mod_by_md5, mod_by_logical = _index_manifest_mods(all_mods)
    entries_by_md5, entries_by_modfile = _entry_lookup(entries)
    stats = RuleStats()
    edges: list[tuple[int, int]] = []
    for layer in layers:
        edges.extend(
            _collect_edges(
                layer.manifest.get("modRules") or [],
                entries,
                mod_by_md5,
                mod_by_logical,
                entries_by_md5,
                entries_by_modfile,
                warnings,
                stats,
            )
        )

    base_rank = {i: i for i in range(len(entries))}
    order_idx, cycle_breaks, cycle_members = _toposort(len(entries), edges, base_rank)
    if cycle_breaks:
        warnings.append(
            f"modRules formed {cycle_breaks} cycle-break(s) among {len(cycle_members)} mod(s); "
            "kept base (layer/phase/manifest) order for the affected mods"
        )

    # A cross-layer rule may drag a base mod behind an add-on mod. That is legal (the
    # curator asked for the ordering) but it breaks the tidy per-layer blocks, so say so.
    layer_crossings = 0
    max_layer = -1
    for pos, idx in enumerate(order_idx):
        current = layer_of[idx]
        if current < max_layer:
            layer_crossings += 1
            if layer_crossings <= 10:
                warnings.append(
                    f"cross-layer rule moved {entries[idx]['folder']!r} (layer "
                    f"{current}) past layer {max_layer} content at position {pos}"
                )
        max_layer = max(max_layer, current)
    if layer_crossings > 10:
        warnings.append(f"... and {layer_crossings - 10} more cross-layer placement(s)")

    return LayeredOrder(
        entries=entries,
        order_idx=order_idx,
        sep_names=sep_names,
        layer_of=layer_of,
        sep_owner=sep_owner,
        shared=shared,
        rules=stats,
        cycle_breaks=cycle_breaks,
        layer_crossings=layer_crossings,
        warnings=warnings,
    )


def build_layered_plugin_order(
    layers: list[Layer], order: LayeredOrder, game_name: str
) -> tuple[list[tuple[str, bool]], list[str], dict[str, int]]:
    """Plugins in base-manifest order, then each add-on's plugins not already listed."""
    ordered: list[tuple[str, bool]] = []
    used: set[str] = set()
    warnings: list[str] = []
    stats = {"in_manifest": 0, "extra": 0}
    for layer in layers:
        idxs = [i for i in order.order_idx if order.layer_of[i] == layer.index]
        if not idxs:
            continue
        sub, sub_warnings, sub_stats = build_plugin_order(
            layer.manifest, order.entries, idxs, game_name
        )
        added = 0
        for name, enabled in sub:
            low = name.lower()
            if low in used:
                continue
            used.add(low)
            ordered.append((name, enabled))
            added += 1
        if added:
            warnings.extend(sub_warnings)
        stats["in_manifest"] += sub_stats["in_manifest"]
        stats["extra"] += sub_stats["extra"]
    return ordered, warnings, stats


# -- Preserving what the user put in the profile ---------------------------------------

_MARKERS = "+-*"


def read_marked_lines(path: Path) -> list[tuple[str, str]]:
    """Parse an MO2 `modlist.txt` / `plugins.txt` into `(marker, name)` in file order."""
    if not path.exists():
        return []
    rows: list[tuple[str, str]] = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        text = line.strip()
        if not text or text.startswith("#"):
            continue
        if text[0] in _MARKERS:
            rows.append((text[0], text[1:]))
        else:
            rows.append(("", text))
    return rows


def splice_preserved(
    new_names: list[str], old_names: list[str], preserved: list[str]
) -> list[str]:
    """Put `preserved` back into `new_names` beside the neighbours they had in `old_names`.

    All three sequences are lowest-priority-first. A preserved name that had nothing
    above it that survived stays above everything: a user mod pinned to the top of
    modlist.txt is still at the top after a layer is added, even though that layer's
    whole block went in beneath it. Otherwise the name lands directly after the nearest
    surviving name below it -- which keeps a run of user mods in its own order, since
    each becomes the next one's anchor -- or, failing that, just below its nearest
    surviving successor.
    """
    result = list(new_names)
    present = set(result)
    positions = {name: i for i, name in enumerate(old_names)}
    for name in preserved:
        if name in present:
            continue
        i = positions.get(name)
        successor = (
            None
            if i is None
            else next(
                (old_names[j] for j in range(i + 1, len(old_names)) if old_names[j] in present),
                None,
            )
        )
        if i is None or successor is None:
            result.append(name)
            present.add(name)
            continue
        anchor = next((old_names[j] for j in range(i - 1, -1, -1) if old_names[j] in present), None)
        if anchor is not None:
            result.insert(result.index(anchor) + 1, name)
        else:
            result.insert(result.index(successor), name)
        present.add(name)
    return result


def render_marked_lines(rows: list[tuple[str, str]], add_dlc_lines: bool = False) -> str:
    """Render `(marker, name)` rows given lowest-priority-first as an MO2 modlist.txt."""
    lines = [HEADER]
    lines.extend(f"{marker}{name}" for marker, name in reversed(rows))
    if add_dlc_lines:
        lines.extend(DLC_LINES)
    return "\n".join(lines) + "\n"


def _mod_plugins_on_disk(folder: Path) -> list[str]:
    if not folder.is_dir():
        return []
    return sorted(p.name for p in folder.iterdir() if p.suffix.lower() in PLUGIN_EXTS)


def plugins_present(mods_dir: Path, game_path: str | None) -> set[str]:
    """Lower-cased names of every plugin that actually exists, in mods/ or the game's Data.

    This is what tells a plugin the user (or MO2) added apart from one left behind by a
    layer that has just been removed: the removed layer's mod folders are gone, so its
    plugins are not on disk any more and drop out of plugins.txt, while base-game
    masters, Creation Club content and user mods stay.
    """
    found: set[str] = set()
    if mods_dir.is_dir():
        for child in mods_dir.iterdir():
            if child.is_dir():
                found.update(name.lower() for name in _mod_plugins_on_disk(child))
    data = Path(game_path) / "Data" if game_path else None
    if data is not None and data.is_dir():
        found.update(p.name.lower() for p in data.iterdir() if p.suffix.lower() in PLUGIN_EXTS)
    return found


def update_mo2_ini(
    ini_path: Path,
    game_name: str,
    game_path: str,
    profile_name: str,
    mo2_version: str,
    exe_blocks: list[dict[str, str]],
) -> list[str]:
    """Write `ModOrganizer.ini` for a new instance, or top up an existing one.

    An instance that has been opened in MO2 (or had `c2wj tools install` run against it)
    carries settings we did not write -- Root Builder's configuration, MO2's own plugin
    state, the game and launcher executables MO2 adds on first start. Re-rendering the
    profile must not throw those away, so an existing file only gains the custom
    executables it is missing; `gamePath` in particular is left alone because `build`
    points it at the Stock Game copy. Returns the executable titles added.
    """
    if not ini_path.exists():
        _write(
            ini_path, render_mo2_ini(game_name, game_path, profile_name, mo2_version, exe_blocks)
        )
        return [b["title"] for b in exe_blocks]
    from . import tools as tools_mod  # local: tools.py is standalone, this avoids a cycle

    was_crlf = b"\r\n" in ini_path.read_bytes()[:65536]
    added = tools_mod.merge_executables(ini_path, exe_blocks)
    if added and was_crlf:
        # merge_executables writes LF; MO2 wrote this file with CRLF and will again. Put
        # the CRLF back, so that adding and then removing a layer is a no-op on the bytes
        # of a file nobody asked us to reformat.
        data = ini_path.read_bytes().replace(b"\r\n", b"\n").replace(b"\n", b"\r\n")
        ini_path.write_bytes(data)
    return added


def render_instance(
    instance_dir: Path | str,
    *,
    led: ledger_mod.Ledger | None = None,
    game_path: str | None = None,
    game_name: str | None = None,
    mo2_version: str = "2.5.2",
    profile_name: str | None = None,
    separators: bool = True,
    disable_optional: bool = False,
    resolution: str = "keep",
    vsync: str = "keep",
    window: str = "keep",
    keep_inis: bool = False,
    report_out: Path | str | None = None,
    reporter: Reporter | None = None,
) -> dict[str, Any]:
    """Render the whole instance profile from every layer in its ledger, plus user mods.

    This is the one profile writer `create`, `add` and `remove` all go through: whatever
    the ledger says the instance is made of right now is what lands in
    `profiles/<name>/`. The ledger is updated in place (separators each layer owns, the
    INI keys it set) and saved. Returns the profile report.
    """
    rep = get_reporter(reporter)
    instance_dir = Path(instance_dir).resolve()
    led = led if led is not None else ledger_mod.load(instance_dir)

    rep.stage("profile")
    layers, warnings = load_layers(instance_dir, led)
    if not layers:
        raise ValueError(f"{instance_dir} has no usable collection layer to render a profile from")

    game = led.data.get("game") or {}
    game_name = game_name or game.get("mo2_name") or ""
    if game_path is None:
        game_path = game.get("stock_game_dir") or game.get("source_path") or ""
    base = layers[0]
    if not profile_name:
        base_record = led.layer(base.slug, base.revision) or {}
        info = base.manifest.get("info") or {}
        profile_name = base_record.get("profile") or sanitize_folder_name(
            info.get("name") or "profile"
        )

    order = compute_layered_order(layers)
    warnings.extend(order.warnings)
    items = build_items_with_separators(order.entries, order.order_idx, order.sep_names, separators)

    mods_dir = instance_dir / "mods"
    mods_dir.mkdir(parents=True, exist_ok=True)
    (instance_dir / "downloads").mkdir(parents=True, exist_ok=True)
    (instance_dir / "overwrite").mkdir(parents=True, exist_ok=True)
    profile_dir = instance_dir / "profiles" / profile_name
    profile_dir.mkdir(parents=True, exist_ok=True)

    # -- separators: folders on disk, and which layer owns each of them ---------------
    separators_by_layer: dict[int, list[str]] = {layer.index: [] for layer in layers}
    separators_created: list[str] = []
    if separators:
        for item in items:
            if item.kind != "separator":
                continue
            sep_dir = mods_dir / item.name
            sep_dir.mkdir(parents=True, exist_ok=True)
            if not (sep_dir / "meta.ini").exists():
                _write(sep_dir / "meta.ini", SEPARATOR_META)
            separators_created.append(item.name)
            separators_by_layer.setdefault(order.sep_owner.get(item.name, 0), []).append(item.name)

    # -- modlist: layer blocks, then the user's own mods back where they were ---------
    managed_rows: list[tuple[str, str]] = []
    for item in items:
        if item.kind == "separator":
            managed_rows.append(("-", item.name))
            continue
        entry = order.entries[item.entry_idx]
        is_optional = bool(entry.get("optional")) or entry.get("phase") == 666
        managed_rows.append(("-" if (is_optional and disable_optional) else "+", entry["folder"]))

    managed_names = [name for _, name in managed_rows]
    managed_set = set(managed_names)

    # -- tool-installed companion mods: after every layer's block, before the user's
    #    own mods. `c2wj tools install` records these in the ledger under `tool:<id>`
    #    (`ledger.tool_owner`); unlike a layer's mods they have no entry in `items`
    #    (they belong to no collection), and unlike a user's mods they *are* known to
    #    the ledger, so without this they would fall into neither list and vanish
    #    from modlist.txt entirely.
    on_disk = {p.name for p in mods_dir.iterdir() if p.is_dir()}
    tool_folders = sorted(
        name
        for name in on_disk
        if name not in managed_set
        and any(o.startswith("tool:") for o in led.owners_of(name))
    )
    managed_rows.extend(("+", name) for name in tool_folders)
    managed_names = [name for _, name in managed_rows]
    managed_set = set(managed_names)

    known_separators = led.separator_folders() | set(separators_created)
    user_folders = sorted(
        name
        for name in on_disk
        if name not in managed_set
        and name not in known_separators
        and name not in led.data["mods"]
    )
    user_set = set(user_folders)

    old_rows = read_marked_lines(profile_dir / "modlist.txt")
    old_ascending = [name for _, name in reversed(old_rows)]
    old_marker = {name: marker for marker, name in old_rows}
    # Kept from the old modlist: the user's own mod folders, plus the DLC and Creation
    # Club rows MO2 writes for itself. Any other name it no longer recognises belonged
    # to a layer that has since been removed.
    preserved = [
        name for name in old_ascending if name in user_set or name.startswith(MO2_PSEUDO_PREFIXES)
    ]
    # A user mod that is not in the old modlist (or there is no old modlist at all) is
    # new to the profile and goes in at the top priority.
    preserved.extend(name for name in user_folders if name not in old_marker)

    final_names = splice_preserved(managed_names, old_ascending, preserved)
    markers = {name: marker for marker, name in managed_rows}
    rows = [(markers.get(name) or old_marker.get(name) or "+", name) for name in final_names]
    add_dlc = game_name == "SkyrimSE" and not any(
        name.startswith("DLC: ") for name in old_ascending
    )

    files_written: list[str] = []
    modlist_path = profile_dir / "modlist.txt"
    _write_keeping_newlines(modlist_path, render_marked_lines(rows, add_dlc))
    files_written.append(str(modlist_path))

    # -- plugins: every layer's, then whatever else is genuinely on disk --------------
    plugin_order, plugin_warnings, plugin_stats = build_layered_plugin_order(
        layers, order, game_name
    )
    warnings.extend(plugin_warnings)
    new_plugin_names = [name for name, _ in plugin_order]
    new_lower = {name.lower() for name in new_plugin_names}
    # Base-game masters, Creation Club content and the user's own plugins: entries MO2
    # or the user put in these files that no layer produced but that do exist on disk.
    present = plugins_present(mods_dir, game_path)
    enabled_by_name = {name: enabled for name, enabled in plugin_order}

    def _merge_plugin_file(name: str, render) -> list[tuple[str, bool]]:
        path = profile_dir / name
        old_file_rows = read_marked_lines(path)
        old_names = [n for _, n in old_file_rows]
        old_markers = {n: m for m, n in old_file_rows}
        keep = [n for n in old_names if n.lower() not in new_lower and n.lower() in present]
        merged = splice_preserved(new_plugin_names, old_names, keep)
        result = [
            (n, enabled_by_name.get(n, old_markers.get(n, "*") == "*")) for n in merged
        ]
        _write_keeping_newlines(path, render(result))
        files_written.append(str(path))
        return result

    plugin_rows = _merge_plugin_file("plugins.txt", render_plugins_txt)
    loadorder_rows = _merge_plugin_file("loadorder.txt", render_loadorder_txt)

    settings_path = profile_dir / "settings.ini"
    _write_keeping_newlines(settings_path, SETTINGS_INI)
    files_written.append(str(settings_path))

    # -- INI tweaks, layer by layer, each key recorded with what it replaced ----------
    if keep_inis:
        rep.log("keep-inis: profile INIs left untouched (no seeding, tweaks, display settings)")
    else:
        seeded_files, seed_notes = seed_profile_inis(profile_dir, game_name, game_path)
        files_written.extend(seeded_files)
        for note in seed_notes:
            rep.log(note)
        for layer in layers:
            record: dict[str, dict[str, dict[str, Any]]] = {}
            notes = apply_collection_ini_tweaks(profile_dir, layer.archive_dir, game_name, record)
            for note in notes:
                rep.log(f"[{layer.slug}] {note}")
            warnings.extend(n for n in notes if n.startswith("INI tweak skipped"))
            led.record_ini_keys(layer.owner, record)
        display_record: dict[str, dict[str, dict[str, Any]]] = {}
        for note in apply_display_settings(
            profile_dir, game_name, resolution, vsync, window, display_record
        ):
            rep.log(note)
        led.record_ini_keys(base.owner, display_record)

        # SkyrimPrefs.ini's [Display] is ignored while a collection's SSE Display Tweaks
        # is enabled; make sure the choice above still applies (or say so if it can't).
        for note in apply_sse_display_tweaks_override(
            profile_dir, mods_dir, game_name, resolution, vsync, window, led
        ):
            rep.log(note)

    # -- ModOrganizer.ini -------------------------------------------------------------
    all_tools = [t for layer in layers for t in (layer.manifest.get("tools") or [])]
    exe_blocks = build_custom_executables(order.entries, all_tools, game_path)
    ini_path = instance_dir / "ModOrganizer.ini"
    added = update_mo2_ini(ini_path, game_name, game_path, profile_name, mo2_version, exe_blocks)
    if added:
        rep.log(f"ModOrganizer.ini: {len(added)} executable(s) registered")
    files_written.append(str(ini_path))

    # -- ledger -----------------------------------------------------------------------
    for layer in layers:
        record = led.layer(layer.slug, layer.revision)
        if record is not None:
            record["separators"] = separators_by_layer.get(layer.index, [])
            record["profile"] = profile_name
    led.save()

    report = {
        "profile": profile_name,
        "mo2_dir": str(instance_dir),
        "layers": [
            {
                "slug": layer.slug,
                "revision": layer.revision,
                "name": layer.name,
                "mods": sum(1 for i in order.layer_of if i == layer.index),
                "separators": separators_by_layer.get(layer.index, []),
            }
            for layer in layers
        ],
        "mod_order": order.folders,
        "separators": separators_created,
        "shared_folders": {f: sorted(set(v)) for f, v in order.shared.items()},
        "tool_mods": tool_folders,
        "user_mods": user_folders,
        "rules": {
            "total": order.rules.total,
            "applied": order.rules.applied,
            "ignored_unresolvable": order.rules.ignored,
            "conflicts": order.rules.conflicts,
            "unsupported_type": order.rules.unsupported,
            "cycle_breaks": order.cycle_breaks,
        },
        "layer_crossings": order.layer_crossings,
        "plugins": {
            "total": len(plugin_rows),
            "in_manifest": plugin_stats["in_manifest"],
            "extra": plugin_stats["extra"],
            "user": len(plugin_rows) - len(new_plugin_names),
            "loadorder": len(loadorder_rows),
        },
        "files_written": files_written,
        "warnings": warnings,
    }
    path = Path(report_out) if report_out else instance_dir / "c2wj" / "profile-report.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, indent=2), encoding="utf-8")

    rep.log(
        f"profile {profile_name!r}: {len(layers)} layer(s), {len(order.entries)} collection "
        f"mod(s), {len(tool_folders)} tool mod(s), {len(user_folders)} user mod(s), "
        f"{len(separators_created)} separator(s)"
    )
    rep.log(
        f"modRules: {order.rules.total} total, {order.rules.applied} applied, "
        f"{order.rules.ignored} ignored (unresolvable), {order.rules.conflicts} conflicts, "
        f"{order.rules.unsupported} unsupported-type, {order.cycle_breaks} cycle-break(s), "
        f"{order.layer_crossings} cross-layer placement(s)"
    )
    rep.log(f"plugins written: {len(plugin_rows)}")
    for w in warnings:
        rep.warn(w)
    rep.done(
        "profile",
        f"{profile_name!r}: {len(rows)} modlist row(s) across {len(layers)} layer(s), "
        f"{len(plugin_rows)} plugin(s)",
    )
    return report


def cmd_profile(args: argparse.Namespace, reporter: Reporter | None = None) -> int:
    rep = get_reporter(reporter)
    owner: str | None = getattr(args, "owner", None) or None
    install_json_path = Path(args.install_json)
    data = json.loads(install_json_path.read_text(encoding="utf-8"))
    manifest_path = Path(data["manifest"])
    manifest = load_manifest(manifest_path)
    game_name: str = data.get("game_name") or ""
    entries: list[dict[str, Any]] = data.get("entries") or []
    mods_dir = Path(data["mods_dir"])

    mo2_dir = Path(args.mo2_dir) if args.mo2_dir else install_json_path.parent
    info = manifest.get("info") or {}
    profile_name = args.profile_name or sanitize_folder_name(info.get("name") or "profile")
    game_path = args.game_path or ""

    rep.stage("profile")
    order_report = _compute_order(manifest, entries)
    warnings: list[str] = list(order_report.warnings)

    items = build_profile_order(entries, order_report.order_idx, args.separators)

    mo2_dir.mkdir(parents=True, exist_ok=True)
    (mo2_dir / "downloads").mkdir(parents=True, exist_ok=True)
    (mo2_dir / "overwrite").mkdir(parents=True, exist_ok=True)
    profile_dir = mo2_dir / "profiles" / profile_name
    profile_dir.mkdir(parents=True, exist_ok=True)

    separators_created: list[str] = []
    if args.separators:
        for item in items:
            if item.kind != "separator":
                continue
            sep_dir = mods_dir / item.name
            sep_dir.mkdir(parents=True, exist_ok=True)
            _write(sep_dir / "meta.ini", SEPARATOR_META)
            separators_created.append(item.name)

    files_written: list[str] = []

    modlist_path = profile_dir / "modlist.txt"
    _write(modlist_path, render_modlist(items, entries, args.disable_optional, game_name))
    files_written.append(str(modlist_path))

    plugin_order, plugin_warnings, plugin_stats = build_plugin_order(
        manifest, entries, order_report.order_idx, game_name
    )
    warnings.extend(plugin_warnings)

    plugins_path = profile_dir / "plugins.txt"
    _write(plugins_path, render_plugins_txt(plugin_order))
    files_written.append(str(plugins_path))

    loadorder_path = profile_dir / "loadorder.txt"
    _write(loadorder_path, render_loadorder_txt(plugin_order))
    files_written.append(str(loadorder_path))

    settings_path = profile_dir / "settings.ini"
    _write(settings_path, SETTINGS_INI)
    files_written.append(str(settings_path))

    ini_keys: dict[str, dict[str, list[str]]] = {}
    if args.keep_inis:
        rep.log("keep-inis: profile INIs left untouched (no seeding, tweaks, display settings)")
    else:
        seeded_files, seed_notes = seed_profile_inis(profile_dir, game_name, game_path)
        files_written.extend(seeded_files)
        for note in seed_notes:
            rep.log(note)

        ini_notes = apply_collection_ini_tweaks(
            profile_dir, manifest_path.parent, game_name, ini_keys
        )
        for note in ini_notes:
            rep.log(note)
        warnings.extend(n for n in ini_notes if n.startswith("INI tweak skipped"))

        display_notes = apply_display_settings(
            profile_dir, game_name, args.resolution, args.vsync, args.window, ini_keys
        )
        for note in display_notes:
            rep.log(note)

    if owner:
        # Record what this layer wrote into the profile INIs, so removing the layer
        # later can tell its keys apart from the user's own edits.
        led = ledger_mod.load(mo2_dir)
        led.record_ini_keys(owner, ini_keys)
        led.save()

    tools = manifest.get("tools") or []
    exe_blocks = build_custom_executables(entries, tools, game_path)
    ini_path = mo2_dir / "ModOrganizer.ini"
    _write(ini_path, render_mo2_ini(game_name, game_path, profile_name, args.mo2_version, exe_blocks))
    files_written.append(str(ini_path))

    report = {
        "profile": profile_name,
        "mo2_dir": str(mo2_dir.resolve()),
        "mod_order": order_report.folders,
        "separators": separators_created,
        "rules": {
            "total": order_report.rules_total,
            "applied": order_report.rules_applied,
            "ignored_unresolvable": order_report.rules_ignored,
            "conflicts": order_report.rules_conflicts,
            "unsupported_type": order_report.rules_unsupported,
            "cycle_breaks": order_report.cycle_breaks,
        },
        "phase_crossings": order_report.phase_crossings,
        "plugins": {
            "total": len(plugin_order),
            "in_manifest": plugin_stats["in_manifest"],
            "extra": plugin_stats["extra"],
        },
        "files_written": files_written,
        "warnings": warnings,
    }
    report_path = Path(args.report_out) if getattr(args, "report_out", None) else mo2_dir / "profile-report.json"
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    files_written.append(str(report_path))

    rep.log(
        f"profile {profile_name!r}: {len(entries)} mod(s) ordered, "
        f"{len(separators_created)} separator(s)"
    )
    rep.log(
        f"modRules: {order_report.rules_total} total, {order_report.rules_applied} applied, "
        f"{order_report.rules_ignored} ignored (unresolvable), {order_report.rules_conflicts} conflicts, "
        f"{order_report.rules_unsupported} unsupported-type, {order_report.cycle_breaks} cycle-break(s)"
    )
    rep.log(f"phase boundary crossings caused by rules: {order_report.phase_crossings}")
    rep.log(
        f"plugins written: {len(plugin_order)} "
        f"({plugin_stats['in_manifest']} in manifest order, {plugin_stats['extra']} extra)"
    )
    rep.log(f"files written: {len(files_written)}")
    for f in files_written:
        rep.log(f"  {f}")
    for w in warnings:
        rep.warn(w)
    rep.done(
        "profile",
        f"{profile_name!r}: {len(order_report.folders)} mod(s), "
        f"{len(separators_created)} separator(s), {len(plugin_order)} plugin(s)",
    )
    return 0


def add_parser(subparsers: argparse._SubParsersAction) -> None:
    p = subparsers.add_parser(
        "profile",
        help="write the MO2 profile (mod order, plugins, ModOrganizer.ini) from install.json",
    )
    p.add_argument("install_json", help="path to install.json written by the installer")
    p.add_argument(
        "--mo2-dir",
        default=None,
        help="portable MO2 instance directory (default: the install.json's directory)",
    )
    p.add_argument(
        "--profile-name",
        default=None,
        help="profile name (default: collection info.name, sanitised)",
    )
    p.add_argument(
        "--game-path",
        default=None,
        help="path to the game install, written to ModOrganizer.ini gamePath (default: empty)",
    )
    p.add_argument(
        "--separators",
        dest="separators",
        action="store_true",
        default=True,
        help="insert phase separators into modlist.txt (default)",
    )
    p.add_argument(
        "--no-separators",
        dest="separators",
        action="store_false",
        help="do not insert phase separators",
    )
    p.add_argument(
        "--mo2-version",
        default="2.5.2",
        help="MO2 version string written to ModOrganizer.ini (default: 2.5.2)",
    )
    p.add_argument(
        "--disable-optional",
        dest="disable_optional",
        action="store_true",
        default=False,
        help="write optional mods as disabled in modlist.txt (default: enabled)",
    )
    p.add_argument(
        "--resolution",
        type=_parse_resolution_arg,
        default="keep",
        help="profile display resolution: 'auto' (detect the primary monitor on Windows), "
        "'keep' (leave existing INI values), or WxH e.g. 3440x1440 (default: keep)",
    )
    p.add_argument(
        "--vsync",
        choices=["on", "off", "keep"],
        default="keep",
        help="profile display vsync (iVSyncPresentInterval): on, off, or keep (default: keep)",
    )
    p.add_argument(
        "--window",
        choices=["fullscreen", "borderless", "windowed", "keep"],
        default="keep",
        help="profile window mode (bFull Screen/bBorderless): fullscreen, borderless, "
        "windowed, or keep (default: keep)",
    )
    p.add_argument(
        "--report-out",
        default=None,
        help="where to write profile-report.json (default: <mo2-dir>/profile-report.json)",
    )
    p.add_argument(
        "--owner",
        default=None,
        help='who this profile belongs to, e.g. "collection:<slug>@<rev>"; the INI keys '
        "written for it are recorded under that owner in the instance ledger",
    )
    p.add_argument(
        "--keep-inis",
        dest="keep_inis",
        action="store_true",
        default=False,
        help="do not touch existing profile INIs at all: skip seeding, collection INI "
        "tweaks, and display settings (for hand-edited INIs)",
    )
    p.set_defaults(func=cmd_profile)


def cmd_profile_instance(args: argparse.Namespace, reporter: Reporter | None = None) -> int:
    """Re-render an existing instance's profile from its ledger.

    A thin `render_instance` wrapper: unlike `c2wj profile` (which builds a single-layer
    profile straight from one `install.json`), this re-renders every layer of an
    *existing* instance -- exactly what `create`/`add`/`remove` do -- so it can be used
    on its own to re-apply --resolution/--vsync/--window (or re-seed INI tweaks) without
    touching mods or layers at all.
    """
    render_instance(
        args.instance,
        resolution=args.resolution,
        vsync=args.vsync,
        window=args.window,
        keep_inis=args.keep_inis,
        reporter=reporter,
    )
    return 0


def add_instance_parser(subparsers: argparse._SubParsersAction) -> None:
    p = subparsers.add_parser(
        "profile-instance",
        help="re-render an existing instance's profile from its ledger (e.g. to change "
        "display settings without a full add/update)",
    )
    p.add_argument("--instance", required=True, help="instance directory (has c2wj-instance.json)")
    p.add_argument(
        "--resolution",
        type=_parse_resolution_arg,
        default="keep",
        help="profile display resolution: 'auto', 'keep', or WxH (default: keep)",
    )
    p.add_argument(
        "--vsync",
        choices=["on", "off", "keep"],
        default="keep",
        help="profile display vsync (default: keep)",
    )
    p.add_argument(
        "--window",
        choices=["fullscreen", "borderless", "windowed", "keep"],
        default="keep",
        help="profile window mode (default: keep)",
    )
    p.add_argument(
        "--keep-inis",
        dest="keep_inis",
        action="store_true",
        default=False,
        help="do not touch existing profile INIs at all",
    )
    p.set_defaults(func=cmd_profile_instance)
