"""Build the MO2 profile (mod order, plugin order, ini files) from install.json.

Consumes the `install.json` written by the installer step (see the module docstring
in `installer.py`) plus the original `collection.json` manifest, and writes a
portable MO2 instance under `--mo2-dir`: `ModOrganizer.ini`, `downloads/`,
`overwrite/`, and `profiles/<profile>/{modlist,plugins,loadorder}.txt` +
`settings.ini`. Mod order is derived from the manifest's install `phase` plus any
`modRules` that resolve to two mods actually present in the collection; plugin
order is derived from mod order plus the manifest's own `plugins[]` load order.
"""

from __future__ import annotations

import argparse
import configparser
import heapq
import json
import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .manifest import load_manifest
from .naming import sanitize_folder_name, separator_name

# MO2 short game name -> the game plugin's display name (ModOrganizer.ini gameName=).
MO2_GAME_DISPLAY_NAMES: dict[str, str] = {
    "SkyrimSE": "Skyrim Special Edition",
    "Skyrim": "Skyrim",
    "SkyrimVR": "Skyrim VR",
    "Fallout4": "Fallout 4",
    "FalloutNV": "New Vegas",
    "Fallout3": "Fallout 3",
    "Oblivion": "Oblivion",
    "Starfield": "Starfield",
    "Enderal": "Enderal",
    "EnderalSE": "Enderal Special Edition",
}

# Base-game master files that MO2 adds itself and that should never be written to
# plugins.txt / loadorder.txt even if a mod entry happens to list one.
BASE_GAME_MASTERS: dict[str, set[str]] = {
    "SkyrimSE": {"skyrim.esm", "update.esm", "dawnguard.esm", "hearthfires.esm", "dragonborn.esm"},
    "Skyrim": {"skyrim.esm", "update.esm", "dawnguard.esm", "hearthfires.esm", "dragonborn.esm"},
    "SkyrimVR": {
        "skyrim.esm",
        "skyrimvr.esm",
        "update.esm",
        "dawnguard.esm",
        "hearthfires.esm",
        "dragonborn.esm",
    },
    "Fallout4": {
        "fallout4.esm",
        "dlcrobot.esm",
        "dlcworkshop01.esm",
        "dlccoast.esm",
        "dlcworkshop02.esm",
        "dlcworkshop03.esm",
        "dlcnukaworld.esm",
    },
    "FalloutNV": {"falloutnv.esm"},
    "Fallout3": {"fallout3.esm"},
    "Oblivion": {"oblivion.esm"},
}

SEP_SUFFIX = "_separator"
SEPARATOR_META = "[General]\nmodid=0\nversion=\nnewestVersion=\ncategory=0\ninstallationFile=\n"
SETTINGS_INI = "[General]\nLocalSaves=false\nLocalSettings=true\nAutomaticArchiveInvalidation=true\n"
HEADER = "# This file was automatically generated by Mod Organizer."
DLC_LINES = ["*DLC: Dragonborn", "*DLC: HearthFires", "*DLC: Dawnguard"]


# -- Ordering -------------------------------------------------------------------


@dataclass
class OrderReport:
    order_idx: list[int]
    folders: list[str]
    rules_total: int
    rules_applied: int
    rules_ignored: int
    rules_conflicts: int
    rules_unsupported: int
    cycle_breaks: int
    phase_crossings: int
    warnings: list[str] = field(default_factory=list)


def _phase_base_key(phase: Any) -> tuple[int, Any]:
    """Sort key placing optional-phase (666) mods after every numbered phase."""
    if phase == 666:
        return (1, 0)
    return (0, phase)


def _index_manifest_mods(mods: list[dict[str, Any]]) -> tuple[dict[str, dict], dict[str, dict]]:
    by_md5: dict[str, dict] = {}
    by_logical: dict[str, dict] = {}
    for mod in mods:
        src = mod.get("source") or {}
        md5 = src.get("md5")
        logical = src.get("logicalFilename")
        if md5:
            by_md5.setdefault(md5, mod)
        if logical:
            by_logical.setdefault(logical, mod)
    return by_md5, by_logical


def _resolve_endpoint(
    endpoint: dict[str, Any], by_md5: dict[str, dict], by_logical: dict[str, dict]
) -> dict | None:
    md5 = endpoint.get("fileMD5")
    if md5 and md5 in by_md5:
        return by_md5[md5]
    logical = endpoint.get("logicalFileName")
    if logical and logical in by_logical:
        return by_logical[logical]
    return None


def _entry_lookup(entries: list[dict[str, Any]]) -> tuple[dict[str, int], dict[tuple, int]]:
    by_md5: dict[str, int] = {}
    by_modfile: dict[tuple, int] = {}
    for i, e in enumerate(entries):
        md5 = e.get("md5")
        if md5:
            by_md5.setdefault(md5, i)
        mod_id, file_id = e.get("mod_id"), e.get("file_id")
        if mod_id is not None and file_id is not None:
            by_modfile.setdefault((mod_id, file_id), i)
    return by_md5, by_modfile


def _entry_index_for_mod(
    mod: dict[str, Any], by_md5: dict[str, int], by_modfile: dict[tuple, int]
) -> int | None:
    src = mod.get("source") or {}
    md5 = src.get("md5")
    if md5 and md5 in by_md5:
        return by_md5[md5]
    key = (src.get("modId"), src.get("fileId"))
    if key in by_modfile:
        return by_modfile[key]
    return None


def _compute_order(manifest: dict[str, Any], entries: list[dict[str, Any]]) -> OrderReport:
    n = len(entries)
    warnings: list[str] = []

    def base_key(i: int) -> tuple:
        return (*_phase_base_key(entries[i].get("phase", 0)), i)

    base_order = sorted(range(n), key=base_key)
    base_rank = {idx: rank for rank, idx in enumerate(base_order)}

    mods = manifest.get("mods") or []
    mod_by_md5, mod_by_logical = _index_manifest_mods(mods)
    entries_by_md5, entries_by_modfile = _entry_lookup(entries)

    rules = manifest.get("modRules") or []
    edges: list[tuple[int, int]] = []
    rules_applied = 0
    rules_ignored = 0
    rules_conflicts = 0
    rules_unsupported = 0

    for rule in rules:
        rtype = rule.get("type")
        src_mod = _resolve_endpoint(rule.get("source") or {}, mod_by_md5, mod_by_logical)
        ref_mod = _resolve_endpoint(rule.get("reference") or {}, mod_by_md5, mod_by_logical)
        if src_mod is None or ref_mod is None:
            rules_ignored += 1
            continue

        src_idx = _entry_index_for_mod(src_mod, entries_by_md5, entries_by_modfile)
        ref_idx = _entry_index_for_mod(ref_mod, entries_by_md5, entries_by_modfile)
        if src_idx is None or ref_idx is None:
            rules_ignored += 1
            warnings.append(
                f"modRule ({rtype}) resolved to manifest mods with no matching install "
                f"entry: {src_mod.get('name')!r} / {ref_mod.get('name')!r}"
            )
            continue
        if src_idx == ref_idx:
            rules_ignored += 1
            continue

        if rtype == "before":
            edges.append((src_idx, ref_idx))
            rules_applied += 1
        elif rtype == "after":
            edges.append((ref_idx, src_idx))
            rules_applied += 1
        elif rtype == "conflicts":
            rules_conflicts += 1
            warnings.append(
                f"modRule conflicts: {entries[src_idx]['folder']!r} <-> "
                f"{entries[ref_idx]['folder']!r} (not reordered)"
            )
        else:
            rules_unsupported += 1
            warnings.append(f"modRule type {rtype!r} between collection mods ignored (unsupported)")

    adjacency: dict[int, list[int]] = {i: [] for i in range(n)}
    indegree: dict[int, int] = {i: 0 for i in range(n)}
    seen_edges: set[tuple[int, int]] = set()
    for a, b in edges:
        if (a, b) in seen_edges:
            continue
        seen_edges.add((a, b))
        adjacency[a].append(b)
        indegree[b] += 1

    remaining = set(range(n))
    heap = [(base_rank[i], i) for i in remaining if indegree[i] == 0]
    heapq.heapify(heap)
    result_idx: list[int] = []
    cycle_breaks = 0
    cycle_members: set[int] = set()

    while remaining:
        if heap:
            _, node = heapq.heappop(heap)
            if node not in remaining:
                continue
        else:
            node = min(remaining, key=lambda i: base_rank[i])
            cycle_breaks += 1
            cycle_members.add(node)
        remaining.discard(node)
        result_idx.append(node)
        for succ in adjacency[node]:
            if succ in remaining:
                indegree[succ] -= 1
                if indegree[succ] == 0:
                    heapq.heappush(heap, (base_rank[succ], succ))

    if cycle_breaks:
        warnings.append(
            f"modRules formed {cycle_breaks} cycle-break(s) among {len(cycle_members)} mod(s); "
            "kept base (phase/manifest) order for the affected mods"
        )

    phase_crossings = 0
    max_seen: tuple | None = None
    for idx in result_idx:
        pr = _phase_base_key(entries[idx].get("phase", 0))
        if max_seen is not None and pr < max_seen:
            phase_crossings += 1
        if max_seen is None or pr > max_seen:
            max_seen = pr

    folders = [entries[i]["folder"] for i in result_idx]

    return OrderReport(
        order_idx=result_idx,
        folders=folders,
        rules_total=len(rules),
        rules_applied=rules_applied,
        rules_ignored=rules_ignored,
        rules_conflicts=rules_conflicts,
        rules_unsupported=rules_unsupported,
        cycle_breaks=cycle_breaks,
        phase_crossings=phase_crossings,
        warnings=warnings,
    )


def order_mods(manifest: dict[str, Any], entries: list[dict[str, Any]]) -> list[str]:
    """Return mod folder names in MO2 priority order, lowest priority first."""
    return _compute_order(manifest, entries).folders


# -- Separators -------------------------------------------------------------------


@dataclass
class ProfileItem:
    kind: str  # "mod" | "separator"
    name: str
    entry_idx: int | None = None
    phase: Any = None


def build_profile_order(
    entries: list[dict[str, Any]], order_idx: list[int], add_separators: bool
) -> list[ProfileItem]:
    """Ascending-priority mod list with a separator inserted after each phase run.

    A separator appears right after the mods of its phase in this ascending
    (lowest-priority-first) list, which puts it directly above that group once the
    list is reversed for modlist.txt (MO2's descending-priority, top-to-bottom view).
    """
    items: list[ProfileItem] = []
    sep_name_counts: dict[str, int] = {}
    run_phase: Any = None
    run_started = False

    def close_run(phase: Any) -> None:
        if not add_separators:
            return
        name = separator_name(phase)
        count = sep_name_counts.get(name, 0)
        sep_name_counts[name] = count + 1
        if count:
            # A rule pulled some mods across a phase boundary, splitting this phase into
            # several runs. One separator per phase is enough; the stragglers simply sit
            # inside the neighbouring section.
            return
        items.append(ProfileItem(kind="separator", name=name, phase=phase))

    for idx in order_idx:
        phase = entries[idx].get("phase", 0)
        if run_started and phase != run_phase:
            close_run(run_phase)
        items.append(ProfileItem(kind="mod", name=entries[idx]["folder"], entry_idx=idx, phase=phase))
        run_phase = phase
        run_started = True
    if run_started:
        close_run(run_phase)
    return items


# -- Plugins ----------------------------------------------------------------------


def build_plugin_order(
    manifest: dict[str, Any], entries: list[dict[str, Any]], order_idx: list[int], game_name: str
) -> tuple[list[tuple[str, bool]], list[str], dict[str, int]]:
    """Plugin load order: manifest plugins[] order first, then extras in mod order."""
    manifest_plugins = manifest.get("plugins") or []
    base_masters = BASE_GAME_MASTERS.get(game_name, set())

    seen: set[str] = set()
    collected: list[tuple[str, int]] = []
    for idx in order_idx:
        for name in entries[idx].get("plugins") or []:
            low = name.lower()
            if low in base_masters or low in seen:
                continue
            seen.add(low)
            collected.append((name, idx))
    collected_by_lower = {name.lower(): (name, idx) for name, idx in collected}

    ordered: list[tuple[str, bool]] = []
    used_lower: set[str] = set()
    for p in manifest_plugins:
        name = p.get("name")
        if not name:
            continue
        low = name.lower()
        if low in base_masters or low in used_lower:
            continue
        if low in collected_by_lower:
            used_lower.add(low)
            ordered.append((name, bool(p.get("enabled", True))))

    warnings: list[str] = []
    extra_count = 0
    for name, idx in collected:
        low = name.lower()
        if low in used_lower:
            continue
        used_lower.add(low)
        ordered.append((name, True))
        extra_count += 1
        warnings.append(
            f"plugin {name!r} (from mod {entries[idx]['folder']!r}) is not in the manifest's "
            "plugins list; enabling by default (likely an unselected FOMOD alternative or an "
            "optional-mod plugin)"
        )

    stats = {"in_manifest": len(ordered) - extra_count, "extra": extra_count}
    return ordered, warnings, stats


# -- Rendering ----------------------------------------------------------------------


def _fwd(path: str | None) -> str:
    return (path or "").replace("\\", "/")


def render_modlist(
    items: list[ProfileItem],
    entries: list[dict[str, Any]],
    disable_optional: bool,
    game_name: str,
) -> str:
    lines = [HEADER]
    for item in reversed(items):
        if item.kind == "separator":
            lines.append(f"-{item.name}")
            continue
        e = entries[item.entry_idx]
        is_optional = bool(e.get("optional")) or e.get("phase") == 666
        enabled = not (is_optional and disable_optional)
        lines.append(f"{'+' if enabled else '-'}{e['folder']}")
    if game_name == "SkyrimSE":
        lines.extend(DLC_LINES)
    return "\n".join(lines) + "\n"


def render_plugins_txt(plugin_order: list[tuple[str, bool]]) -> str:
    lines = [HEADER]
    lines.extend(f"*{name}" if enabled else name for name, enabled in plugin_order)
    return "\n".join(lines) + "\n"


def render_loadorder_txt(plugin_order: list[tuple[str, bool]]) -> str:
    lines = [HEADER]
    lines.extend(name for name, _ in plugin_order)
    return "\n".join(lines) + "\n"


def build_custom_executables(
    entries: list[dict[str, Any]], tools: list[dict[str, Any]], game_path: str
) -> list[dict[str, str]]:
    gp = _fwd(game_path)
    blocks: list[dict[str, str]] = []

    has_script_extender_mod = any("Script Extender" in (e.get("folder") or "") for e in entries)
    has_dinput_skse = any(
        e.get("mod_type") == "dinput" and "SKSE" in (e.get("name") or e.get("folder") or "")
        for e in entries
    )
    if has_script_extender_mod or has_dinput_skse:
        binary = f"{gp}/skse64_loader.exe" if gp else "skse64_loader.exe"
        blocks.append(
            {
                "title": "SKSE",
                "binary": binary,
                "arguments": "",
                "workingDirectory": gp,
                "hide": "false",
                "ownicon": "true",
                "steamAppID": "",
                "toolbar": "true",
            }
        )

    seen_binaries = {b["binary"].lower() for b in blocks}
    for tool in tools:
        exe = _fwd(tool.get("exe") or "")
        binary = f"{gp}/{exe}" if gp else exe
        if binary.lower() in seen_binaries:
            continue  # the manifest lists SKSE too; keep our single entry
        seen_binaries.add(binary.lower())
        # A curator's cwd is their own machine's path; only keep it if it exists here.
        raw_cwd = tool.get("cwd") or ""
        cwd = _fwd(raw_cwd) if raw_cwd and Path(raw_cwd).exists() else gp
        args = tool.get("args") or []
        blocks.append(
            {
                "title": tool.get("name") or "",
                "binary": binary,
                "arguments": " ".join(str(a) for a in args),
                "workingDirectory": cwd,
                "hide": "false",
                "ownicon": "true",
                "steamAppID": "",
                "toolbar": "true",
            }
        )
    return blocks


def render_mo2_ini(
    game_name: str,
    game_path: str,
    profile_name: str,
    mo2_version: str,
    exe_blocks: list[dict[str, str]],
) -> str:
    display_name = MO2_GAME_DISPLAY_NAMES.get(game_name, game_name)
    # MO2 stores gamePath as a QByteArray with native separators, backslashes doubled.
    # Writing it in that form (plus game_edition) makes the instance recognisable as a
    # portable one without needing `build` to rewrite it afterwards.
    native = game_path.replace("/", "\\").replace("\\", "\\\\") if game_path else ""
    game_path_line = f"gamePath=@ByteArray({native})" if game_path else "gamePath="
    lines = [
        "[General]",
        f"gameName={display_name}",
        game_path_line,
        f"selected_profile=@ByteArray({profile_name})",
        f"version={mo2_version}",
        "first_start=false",
        "game_edition=Steam",
        "",
        "[Settings]",
        "style=",
        "",
        "[customExecutables]",
        f"size={len(exe_blocks)}",
    ]
    for i, b in enumerate(exe_blocks, start=1):
        lines.append(f"{i}\\title={b['title']}")
        lines.append(f"{i}\\binary={b['binary']}")
        lines.append(f"{i}\\arguments={b['arguments']}")
        lines.append(f"{i}\\workingDirectory={b['workingDirectory']}")
        lines.append(f"{i}\\hide={b['hide']}")
        lines.append(f"{i}\\ownicon={b['ownicon']}")
        lines.append(f"{i}\\steamAppID={b['steamAppID']}")
        lines.append(f"{i}\\toolbar={b['toolbar']}")
    return "\n".join(lines) + "\n"


def _write(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8", newline="\n")


# -- Command ----------------------------------------------------------------------


# -- Profile-local game INIs -------------------------------------------------------

# MO2 short game name -> (My Games folder, [INI basenames], vanilla default INI in the game dir)
GAME_INIS: dict[str, tuple[str, list[str], str]] = {
    "SkyrimSE": ("Skyrim Special Edition", ["Skyrim.ini", "SkyrimPrefs.ini", "SkyrimCustom.ini"], "Skyrim_Default.ini"),
    "SkyrimVR": ("Skyrim VR", ["Skyrim.ini", "SkyrimPrefs.ini", "SkyrimCustom.ini"], "Skyrim_Default.ini"),
    "Skyrim": ("Skyrim", ["Skyrim.ini", "SkyrimPrefs.ini"], "Skyrim_default.ini"),
    "Fallout4": ("Fallout4", ["Fallout4.ini", "Fallout4Prefs.ini", "Fallout4Custom.ini"], "Fallout4_Default.ini"),
    "FalloutNV": ("FalloutNV", ["Fallout.ini", "FalloutPrefs.ini"], "Fallout_default.ini"),
    "Fallout3": ("Fallout3", ["Fallout.ini", "FalloutPrefs.ini"], "Fallout_default.ini"),
    "Oblivion": ("Oblivion", ["Oblivion.ini"], "Oblivion_default.ini"),
    "Starfield": ("Starfield", ["Starfield.ini", "StarfieldPrefs.ini", "StarfieldCustom.ini"], "Starfield_Default.ini"),
}


def seed_profile_inis(profile_dir: Path, game_name: str, game_path: str) -> tuple[list[str], list[str]]:
    """Create the profile-local game INIs MO2 expects when LocalSettings=true.

    Prefers the user's current INIs from Documents/My Games (they already match the
    installed game version), falls back to the game's shipped *_Default.ini for the
    main INI and empty files for the rest. Existing profile INIs are left alone.

    Returns `(files_written, notes)`; `notes` is a single-element list summarising where the
    written INIs came from (My Games path / *_Default.ini / empty), so users can tell why a
    profile INI has (or lacks) particular values.
    """
    spec = GAME_INIS.get(game_name)
    if not spec:
        return [], []
    my_games_dir, names, default_ini = spec
    my_games = Path.home() / "Documents" / "My Games" / my_games_dir
    written: list[str] = []
    sources: list[str] = []
    for i, name in enumerate(names):
        dest = profile_dir / name
        if dest.exists():
            continue
        src = my_games / name
        if src.exists():
            shutil.copy2(src, dest)
            source = f"My Games ({my_games})"
        elif i == 0 and game_path and (Path(game_path) / default_ini).exists():
            shutil.copy2(Path(game_path) / default_ini, dest)
            source = f"game default ({Path(game_path) / default_ini})"
        else:
            dest.write_text("", encoding="utf-8")
            source = "empty (no source found)"
        written.append(str(dest))
        if source not in sources:
            sources.append(source)

    if not written:
        notes = ["seed INIs: none written (profile INIs already existed)"]
    else:
        notes = [f"seed INIs from: {'; '.join(sources)}"]
    return written, notes


_INI_TWEAK_TARGET = re.compile(r"\[([^\[\]]+)\]\.ini$", re.IGNORECASE)


def merge_ini_values(target: Path, section: str, values: dict[str, str]) -> int:
    """Set/override `values` (key -> value) within `section` of a game INI, line-based.

    Comments, ordering and odd lines elsewhere in the file survive; the section is created
    at the end of the file if missing, and unknown keys are appended within it. Returns the
    number of keys applied.
    """
    lines = target.read_text(encoding="utf-8-sig").splitlines() if target.exists() else []
    start = next((i for i, ln in enumerate(lines) if ln.strip().lower() == f"[{section.lower()}]"), None)
    if start is None:
        if lines and lines[-1].strip():
            lines.append("")
        lines.append(f"[{section}]")
        start = len(lines) - 1
    end = next((i for i in range(start + 1, len(lines)) if lines[i].strip().startswith("[")), len(lines))
    applied = 0
    for key, value in values.items():
        new_line = f"{key}={value}"
        hit = next(
            (i for i in range(start + 1, end) if lines[i].split("=", 1)[0].strip().lower() == key.lower()),
            None,
        )
        if hit is None:
            lines.insert(end, new_line)
            end += 1
        else:
            lines[hit] = new_line
        applied += 1
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return applied


def merge_ini_tweak(target: Path, tweak: Path) -> int:
    """Apply a Vortex INI tweak file onto a game INI: set/override each key in its section.

    Line-based (via `merge_ini_values`) so comments, ordering and odd lines in the game INI
    survive. Returns the number of keys applied.
    """
    tweak_cp = configparser.RawConfigParser(strict=False, delimiters=("=",), interpolation=None)
    tweak_cp.optionxform = str  # type: ignore[assignment]
    tweak_cp.read(tweak, encoding="utf-8-sig")

    applied = 0
    for section in tweak_cp.sections():
        applied += merge_ini_values(target, section, dict(tweak_cp.items(section)))
    return applied


def apply_collection_ini_tweaks(profile_dir: Path, archive_dir: Path, game_name: str) -> list[str]:
    """Apply the collection archive's `INI Tweaks/<name> [Skyrim].ini` files to the profile INIs."""
    tweaks_dir = archive_dir / "INI Tweaks"
    if not tweaks_dir.is_dir():
        return []
    spec = GAME_INIS.get(game_name)
    known = {n.lower()[:-4]: n for n in (spec[1] if spec else [])}  # "skyrimprefs" -> "SkyrimPrefs.ini"
    notes: list[str] = []
    for tweak in sorted(tweaks_dir.glob("*.ini")):
        m = _INI_TWEAK_TARGET.search(tweak.name)
        target_name = known.get(m.group(1).lower()) if m else None
        if not target_name:
            notes.append(f"INI tweak skipped (cannot tell which INI it targets): {tweak.name}")
            continue
        n = merge_ini_tweak(profile_dir / target_name, tweak)
        notes.append(f"INI tweak applied: {tweak.name} -> {target_name} ({n} keys)")
    return notes


def _prefs_ini_name(game_name: str) -> str | None:
    """The `*Prefs.ini` (display settings) file for a game, per `GAME_INIS`."""
    spec = GAME_INIS.get(game_name)
    if not spec:
        return None
    names = spec[1]
    if not names:
        return None
    return next((n for n in names if "prefs" in n.lower()), names[0])


def _detect_resolution() -> tuple[int, int] | None:
    """Detect the primary monitor's current resolution on Windows via ctypes.

    Returns `None` (caller falls back to `keep`) on non-Windows platforms or if the Win32
    calls fail for any reason.
    """
    import sys

    if sys.platform != "win32":
        return None
    try:
        import ctypes

        user32 = ctypes.windll.user32  # type: ignore[attr-defined]
        user32.SetProcessDPIAware()
        width = user32.GetSystemMetrics(0)
        height = user32.GetSystemMetrics(1)
    except Exception:  # noqa: BLE001 - detection is best-effort, fall back to keep
        return None
    if width <= 0 or height <= 0:
        return None
    return width, height


_RESOLUTION_RE = re.compile(r"^(\d+)x(\d+)$", re.IGNORECASE)


def _parse_resolution_arg(value: str) -> str:
    """argparse `type=` for --resolution: 'auto', 'keep', or WxH, validated at parse time."""
    if value in ("auto", "keep") or _RESOLUTION_RE.match(value):
        return value
    raise argparse.ArgumentTypeError(f"must be 'auto', 'keep', or WxH e.g. 3440x1440 (got {value!r})")


def apply_display_settings(
    profile_dir: Path,
    game_name: str,
    resolution: str,
    vsync: str,
    window: str,
) -> list[str]:
    """Apply --resolution/--vsync/--window overrides to the profile's `*Prefs.ini` [Display].

    `resolution` is `auto` (detect the primary monitor via Windows APIs, falling back to
    `keep` if that's not possible), `keep`, or an explicit `WxH` string. `vsync` is
    `on`/`off`/`keep`; `window` is `fullscreen`/`borderless`/`windowed`/`keep`. Applied after
    the collection's own INI Tweaks, so these settings win. Returns a single-element list with
    a human-readable summary line (empty list if the game has no known Prefs INI).
    """
    target_name = _prefs_ini_name(game_name)
    if not target_name:
        return []
    target = profile_dir / target_name

    values: dict[str, str] = {}

    if resolution == "keep":
        res_label = "kept"
    elif resolution == "auto":
        detected = _detect_resolution()
        if detected:
            w, h = detected
            values["iSize W"] = str(w)
            values["iSize H"] = str(h)
            res_label = f"{w}x{h}"
        else:
            res_label = "kept (auto-detect unavailable)"
    else:
        m = _RESOLUTION_RE.match(resolution)
        if not m:
            raise ValueError(f"--resolution must be 'auto', 'keep', or WxH (got {resolution!r})")
        w, h = int(m.group(1)), int(m.group(2))
        values["iSize W"] = str(w)
        values["iSize H"] = str(h)
        res_label = f"{w}x{h}"

    if vsync == "on":
        values["iVSyncPresentInterval"] = "1"
        vsync_label = "on"
    elif vsync == "off":
        values["iVSyncPresentInterval"] = "0"
        vsync_label = "off"
    else:
        vsync_label = "kept"

    # Skyrim SE's launcher writes borderless as bFull Screen=1 + bBorderless=1.
    if window == "fullscreen":
        values["bFull Screen"] = "1"
        values["bBorderless"] = "0"
        window_label = "fullscreen"
    elif window == "borderless":
        values["bFull Screen"] = "1"
        values["bBorderless"] = "1"
        window_label = "borderless"
    elif window == "windowed":
        values["bFull Screen"] = "0"
        values["bBorderless"] = "0"
        window_label = "windowed"
    else:
        window_label = "kept"

    if values:
        merge_ini_values(target, "Display", values)

    return [f"display: {res_label}, vsync {vsync_label}, window {window_label} ({target_name})"]


def cmd_profile(args: argparse.Namespace) -> int:
    install_json_path = Path(args.install_json)
    data = json.loads(install_json_path.read_text(encoding="utf-8"))
    manifest_path = Path(data["manifest"])
    manifest = load_manifest(manifest_path)
    game_name: str = data.get("game_name") or ""
    entries: list[dict[str, Any]] = data.get("entries") or []
    mods_dir = Path(data["mods_dir"])

    mo2_dir = Path(args.mo2_dir) if args.mo2_dir else install_json_path.parent
    info = manifest.get("info") or {}
    profile_name = args.profile_name or sanitize_folder_name(info.get("name") or "profile")
    game_path = args.game_path or ""

    order_report = _compute_order(manifest, entries)
    warnings: list[str] = list(order_report.warnings)

    items = build_profile_order(entries, order_report.order_idx, args.separators)

    mo2_dir.mkdir(parents=True, exist_ok=True)
    (mo2_dir / "downloads").mkdir(parents=True, exist_ok=True)
    (mo2_dir / "overwrite").mkdir(parents=True, exist_ok=True)
    profile_dir = mo2_dir / "profiles" / profile_name
    profile_dir.mkdir(parents=True, exist_ok=True)

    separators_created: list[str] = []
    if args.separators:
        for item in items:
            if item.kind != "separator":
                continue
            sep_dir = mods_dir / item.name
            sep_dir.mkdir(parents=True, exist_ok=True)
            _write(sep_dir / "meta.ini", SEPARATOR_META)
            separators_created.append(item.name)

    files_written: list[str] = []

    modlist_path = profile_dir / "modlist.txt"
    _write(modlist_path, render_modlist(items, entries, args.disable_optional, game_name))
    files_written.append(str(modlist_path))

    plugin_order, plugin_warnings, plugin_stats = build_plugin_order(
        manifest, entries, order_report.order_idx, game_name
    )
    warnings.extend(plugin_warnings)

    plugins_path = profile_dir / "plugins.txt"
    _write(plugins_path, render_plugins_txt(plugin_order))
    files_written.append(str(plugins_path))

    loadorder_path = profile_dir / "loadorder.txt"
    _write(loadorder_path, render_loadorder_txt(plugin_order))
    files_written.append(str(loadorder_path))

    settings_path = profile_dir / "settings.ini"
    _write(settings_path, SETTINGS_INI)
    files_written.append(str(settings_path))

    if args.keep_inis:
        print("keep-inis: profile INIs left untouched (skipping seeding, tweaks, display settings)")
    else:
        seeded_files, seed_notes = seed_profile_inis(profile_dir, game_name, game_path)
        files_written.extend(seeded_files)
        for note in seed_notes:
            print(note)

        ini_notes = apply_collection_ini_tweaks(profile_dir, manifest_path.parent, game_name)
        for note in ini_notes:
            print(note)
        warnings.extend(n for n in ini_notes if n.startswith("INI tweak skipped"))

        display_notes = apply_display_settings(
            profile_dir, game_name, args.resolution, args.vsync, args.window
        )
        for note in display_notes:
            print(note)

    tools = manifest.get("tools") or []
    exe_blocks = build_custom_executables(entries, tools, game_path)
    ini_path = mo2_dir / "ModOrganizer.ini"
    _write(ini_path, render_mo2_ini(game_name, game_path, profile_name, args.mo2_version, exe_blocks))
    files_written.append(str(ini_path))

    report = {
        "profile": profile_name,
        "mo2_dir": str(mo2_dir.resolve()),
        "mod_order": order_report.folders,
        "separators": separators_created,
        "rules": {
            "total": order_report.rules_total,
            "applied": order_report.rules_applied,
            "ignored_unresolvable": order_report.rules_ignored,
            "conflicts": order_report.rules_conflicts,
            "unsupported_type": order_report.rules_unsupported,
            "cycle_breaks": order_report.cycle_breaks,
        },
        "phase_crossings": order_report.phase_crossings,
        "plugins": {
            "total": len(plugin_order),
            "in_manifest": plugin_stats["in_manifest"],
            "extra": plugin_stats["extra"],
        },
        "files_written": files_written,
        "warnings": warnings,
    }
    report_path = mo2_dir / "profile-report.json"
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    files_written.append(str(report_path))

    print(f"profile {profile_name!r}: {len(entries)} mod(s) ordered, {len(separators_created)} separator(s)")
    print(
        f"modRules: {order_report.rules_total} total, {order_report.rules_applied} applied, "
        f"{order_report.rules_ignored} ignored (unresolvable), {order_report.rules_conflicts} conflicts, "
        f"{order_report.rules_unsupported} unsupported-type, {order_report.cycle_breaks} cycle-break(s)"
    )
    print(f"phase boundary crossings caused by rules: {order_report.phase_crossings}")
    print(
        f"plugins written: {len(plugin_order)} "
        f"({plugin_stats['in_manifest']} in manifest order, {plugin_stats['extra']} extra)"
    )
    print(f"files written: {len(files_written)}")
    for f in files_written:
        print(f"  {f}")
    if warnings:
        print(f"warnings ({len(warnings)}):")
        for w in warnings:
            print(f"  - {w}")
    return 0


def add_parser(subparsers: argparse._SubParsersAction) -> None:
    p = subparsers.add_parser(
        "profile",
        help="write the MO2 profile (mod order, plugins, ModOrganizer.ini) from install.json",
    )
    p.add_argument("install_json", help="path to install.json written by the installer")
    p.add_argument(
        "--mo2-dir",
        default=None,
        help="portable MO2 instance directory (default: the install.json's directory)",
    )
    p.add_argument(
        "--profile-name",
        default=None,
        help="profile name (default: collection info.name, sanitised)",
    )
    p.add_argument(
        "--game-path",
        default=None,
        help="path to the game install, written to ModOrganizer.ini gamePath (default: empty)",
    )
    p.add_argument(
        "--separators",
        dest="separators",
        action="store_true",
        default=True,
        help="insert phase separators into modlist.txt (default)",
    )
    p.add_argument(
        "--no-separators",
        dest="separators",
        action="store_false",
        help="do not insert phase separators",
    )
    p.add_argument(
        "--mo2-version",
        default="2.5.2",
        help="MO2 version string written to ModOrganizer.ini (default: 2.5.2)",
    )
    p.add_argument(
        "--disable-optional",
        dest="disable_optional",
        action="store_true",
        default=False,
        help="write optional mods as disabled in modlist.txt (default: enabled)",
    )
    p.add_argument(
        "--resolution",
        type=_parse_resolution_arg,
        default="auto",
        help="profile display resolution: 'auto' (detect the primary monitor on Windows), "
        "'keep' (leave existing INI values), or WxH e.g. 3440x1440 (default: auto)",
    )
    p.add_argument(
        "--vsync",
        choices=["on", "off", "keep"],
        default="keep",
        help="profile display vsync (iVSyncPresentInterval): on, off, or keep (default: keep)",
    )
    p.add_argument(
        "--window",
        choices=["fullscreen", "borderless", "windowed", "keep"],
        default="keep",
        help="profile window mode (bFull Screen/bBorderless): fullscreen, borderless, "
        "windowed, or keep (default: keep)",
    )
    p.add_argument(
        "--keep-inis",
        dest="keep_inis",
        action="store_true",
        default=False,
        help="do not touch existing profile INIs at all: skip seeding, collection INI "
        "tweaks, and display settings (for hand-edited INIs)",
    )
    p.set_defaults(func=cmd_profile)
